//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.07.12 at 11:19:10 PM IST 
//


package com.ngen.cosys.service.volumetricscanner.model;

/*import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;*/

import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlProperty;
import com.fasterxml.jackson.dataformat.xml.annotation.JacksonXmlRootElement;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="messageId" type="{http://www.w3.org/2001/XMLSchema}long"/>
 *         &lt;element name="awb" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="hawb" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="smartGateID" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
/*@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "messageId",
    "awb",
    "hawb"
})
@XmlRootElement(name = "cancelScanVolWgtRequest")*/
@JsonPropertyOrder(value = { "messageId", "awb", "hawb" })
@JacksonXmlRootElement(localName = "cancelScanVolWgtRequest")
public class CancelScanVolWgtRequest {

    @JacksonXmlProperty(localName = "messageId")
    protected long messageId;
    // @XmlElement(required = true)
    @JacksonXmlProperty(localName = "awb")
    protected String awb;
    // @XmlElement(required = true)
    @JacksonXmlProperty(localName = "hawb")
    protected String hawb;
    // @XmlElement(required = true)
    // protected String smartGateID;

    /**
     * Gets the value of the messageId property.
     * 
     */
    public long getMessageId() {
        return messageId;
    }

    /**
     * Sets the value of the messageId property.
     * 
     */
    public void setMessageId(long value) {
        this.messageId = value;
    }

    /**
     * Gets the value of the awb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAwb() {
        return awb;
    }

    /**
     * Sets the value of the awb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAwb(String value) {
        this.awb = value;
    }

    /**
     * Gets the value of the hawb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHawb() {
        return hawb;
    }

    /**
     * Sets the value of the hawb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHawb(String value) {
        this.hawb = value;
    }

    /**
     * Gets the value of the smartGateID property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
//    public String getSmartGateID() {
//        return smartGateID;
//    }
//
//    /**
//     * Sets the value of the smartGateID property.
//     * 
//     * @param value
//     *     allowed object is
//     *     {@link String }
//     *     
//     */
//    public void setSmartGateID(String value) {
//        this.smartGateID = value;
//    }

}
