package com.ngen.cosys.billing.sap.enums;

public enum FileFolder {
   
   SAP_O094_INBOUND_TOPROCESS("SAP_O094_INBOUND_TOPROCESS"),
   SAP_O094_INBOUND_PROCESSING("SAP_O094_INBOUND_PROCESSING"), 
   SAP_O094_INBOUND_ARCHIVED("SAP_O094_INBOUND_ARCHIVED"), 
   
   SAP_O095_INBOUND_TOPROCESS("SAP_O095_INBOUND_TOPROCESS"),
   SAP_O095_INBOUND_PROCESSING("SAP_O095_INBOUND_PROCESSING"), 
   SAP_O095_INBOUND_ARCHIVED("SAP_O095_INBOUND_ARCHIVED"), 
   
   SAP_O096_INBOUND_TOPROCESS("SAP_O096_INBOUND_TOPROCESS"),
   SAP_O096_INBOUND_PROCESSING("SAP_O096_INBOUND_PROCESSING"), 
   SAP_O096_INBOUND_ARCHIVED("SAP_O096_INBOUND_ARCHIVED"), 
   
   SAP_O097_INBOUND_TOPROCESS("SAP_O097_INBOUND_TOPROCESS"),
   SAP_O097_INBOUND_PROCESSING("SAP_O097_INBOUND_PROCESSING"), 
   SAP_O097_INBOUND_ARCHIVED("SAP_O097_INBOUND_ARCHIVED"), 
   
   SAP_AP_OUTBOUND_TOPROCESS("SAP_AP_OUTBOUND_TOPROCESS"),
   SAP_AP_OUTBOUND_PROCESSING("SAP_AP_OUTBOUND_PROCESSING"),
   SAP_AP_OUTBOUND_ARCHIVED("SAP_AP_OUTBOUND_ARCHIVED"),
   
   SAP_SD_OUTBOUND_TOPROCESS("SAP_I062_OUTBOUND_TOPROCESS"),
   SAP_SD_OUTBOUND_PROCESSING("SAP_I062_OUTBOUND_PROCESSING"),
   SAP_SD_OUTBOUND_ARCHIVED("SAP_I062_OUTBOUND_ARCHIVED");

   private final String value;

   private FileFolder(String value) {
       this.value = value;
   }

   /**
    * Value
    * 
    * @return Value
    */
   public String value() {
       return this.value;
   }

   /*
    * (non-Javadoc)
    * 
    * @see java.lang.Enum#toString()
    */
   @Override
   public String toString() {
       return String.valueOf(this.value);
   }
}
