//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.20 at 04:46:06 PM SGT 
//


package com.ibsplc.icargo.business.admin.accesscontrol.types.standard;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for fileStoreInfoType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="fileStoreInfoType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="companyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="environmentType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="storageMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="transferModeDetails" type="{http://www.ibsplc.com/icargo/services/types/AdminAccessControlService/standard/2012/12/12_01}transferModeDetailsType" maxOccurs="unbounded"/>
 *         &lt;element name="fileInfo" type="{http://www.ibsplc.com/icargo/services/types/AdminAccessControlService/standard/2012/12/12_01}fileInfoType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "fileStoreInfoType", propOrder = {
    "companyCode",
    "environmentType",
    "storageMode",
    "transferModeDetails",
    "fileInfo"
})
public class FileStoreInfoType {

    @XmlElement(required = true)
    protected String companyCode;
    @XmlElement(required = true)
    protected String environmentType;
    @XmlElement(required = true)
    protected String storageMode;
    @XmlElement(required = true)
    protected List<TransferModeDetailsType> transferModeDetails;
    @XmlElement(required = true)
    protected List<FileInfoType> fileInfo;

    /**
     * Gets the value of the companyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * Sets the value of the companyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyCode(String value) {
        this.companyCode = value;
    }

    /**
     * Gets the value of the environmentType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEnvironmentType() {
        return environmentType;
    }

    /**
     * Sets the value of the environmentType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEnvironmentType(String value) {
        this.environmentType = value;
    }

    /**
     * Gets the value of the storageMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStorageMode() {
        return storageMode;
    }

    /**
     * Sets the value of the storageMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStorageMode(String value) {
        this.storageMode = value;
    }

    /**
     * Gets the value of the transferModeDetails property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the transferModeDetails property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getTransferModeDetails().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link TransferModeDetailsType }
     * 
     * 
     */
    public List<TransferModeDetailsType> getTransferModeDetails() {
        if (transferModeDetails == null) {
            transferModeDetails = new ArrayList<TransferModeDetailsType>();
        }
        return this.transferModeDetails;
    }

    /**
     * Gets the value of the fileInfo property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the fileInfo property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFileInfo().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link FileInfoType }
     * 
     * 
     */
    public List<FileInfoType> getFileInfo() {
        if (fileInfo == null) {
            fileInfo = new ArrayList<FileInfoType>();
        }
        return this.fileInfo;
    }

}
