//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.20 at 04:46:06 PM SGT 
//


package com.ibsplc.icargo.business.admin.accesscontrol.types.standard;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for LoginResponseType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoginResponseType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="sessionId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="language" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="country" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="stationCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="ownAirlineCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="airportCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="defaultWarehouseCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="companyCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="roleGroupCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="userId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dateFormat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="timeFormat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="dateAndTimeFormat" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="error" type="{http://www.ibsplc.com/icargo/services/types/AdminAccessControlService/standard/2012/12/12_01}ErrorDetailType" minOccurs="0"/>
 *         &lt;element name="ownAirlineIdentifier" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="defaultOfficeCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="airportDateAndTime" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="timeZoneInformation" type="{http://www.ibsplc.com/icargo/services/types/AdminAccessControlService/standard/2012/12/12_01}TimeZoneInformationType" minOccurs="0"/>
 *         &lt;element name="userParameters" type="{http://www.ibsplc.com/icargo/services/types/AdminAccessControlService/standard/2012/12/12_01}UserParameterType" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element name="passwordChangeRequired" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="portalUserDetails" type="{http://www.ibsplc.com/icargo/services/types/AdminAccessControlService/standard/2012/12/12_01}portalUserDetailsType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoginResponseType", propOrder = {
    "sessionId",
    "language",
    "country",
    "stationCode",
    "ownAirlineCode",
    "airportCode",
    "defaultWarehouseCode",
    "companyCode",
    "roleGroupCode",
    "userId",
    "dateFormat",
    "timeFormat",
    "dateAndTimeFormat",
    "error",
    "ownAirlineIdentifier",
    "defaultOfficeCode",
    "airportDateAndTime",
    "timeZoneInformation",
    "userParameters",
    "passwordChangeRequired",
    "portalUserDetails"
})
@XmlRootElement(name = "loginResponse")
public class LoginResponseType {

    @XmlElement(required = true)
    protected String sessionId;
    protected String language;
    protected String country;
    @XmlElement(required = true)
    protected String stationCode;
    @XmlElement(required = true)
    protected String ownAirlineCode;
    @XmlElement(required = true)
    protected String airportCode;
    protected String defaultWarehouseCode;
    @XmlElement(required = true)
    protected String companyCode;
    @XmlElement(required = true)
    protected String roleGroupCode;
    @XmlElement(required = true)
    protected String userId;
    @XmlElement(required = true)
    protected String dateFormat;
    @XmlElement(required = true)
    protected String timeFormat;
    @XmlElement(required = true)
    protected String dateAndTimeFormat;
    protected ErrorDetailType error;
    protected int ownAirlineIdentifier;
    @XmlElement(required = true)
    protected String defaultOfficeCode;
    @XmlElement(required = true)
    protected String airportDateAndTime;
    protected TimeZoneInformationType timeZoneInformation;
    protected List<UserParameterType> userParameters;
    protected String passwordChangeRequired;
    protected PortalUserDetailsType portalUserDetails;

    /**
     * Gets the value of the sessionId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSessionId() {
        return sessionId;
    }

    /**
     * Sets the value of the sessionId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSessionId(String value) {
        this.sessionId = value;
    }

    /**
     * Gets the value of the language property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLanguage() {
        return language;
    }

    /**
     * Sets the value of the language property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLanguage(String value) {
        this.language = value;
    }

    /**
     * Gets the value of the country property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCountry() {
        return country;
    }

    /**
     * Sets the value of the country property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCountry(String value) {
        this.country = value;
    }

    /**
     * Gets the value of the stationCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getStationCode() {
        return stationCode;
    }

    /**
     * Sets the value of the stationCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setStationCode(String value) {
        this.stationCode = value;
    }

    /**
     * Gets the value of the ownAirlineCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOwnAirlineCode() {
        return ownAirlineCode;
    }

    /**
     * Sets the value of the ownAirlineCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOwnAirlineCode(String value) {
        this.ownAirlineCode = value;
    }

    /**
     * Gets the value of the airportCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirportCode() {
        return airportCode;
    }

    /**
     * Sets the value of the airportCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirportCode(String value) {
        this.airportCode = value;
    }

    /**
     * Gets the value of the defaultWarehouseCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultWarehouseCode() {
        return defaultWarehouseCode;
    }

    /**
     * Sets the value of the defaultWarehouseCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultWarehouseCode(String value) {
        this.defaultWarehouseCode = value;
    }

    /**
     * Gets the value of the companyCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCompanyCode() {
        return companyCode;
    }

    /**
     * Sets the value of the companyCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCompanyCode(String value) {
        this.companyCode = value;
    }

    /**
     * Gets the value of the roleGroupCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoleGroupCode() {
        return roleGroupCode;
    }

    /**
     * Sets the value of the roleGroupCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoleGroupCode(String value) {
        this.roleGroupCode = value;
    }

    /**
     * Gets the value of the userId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserId() {
        return userId;
    }

    /**
     * Sets the value of the userId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserId(String value) {
        this.userId = value;
    }

    /**
     * Gets the value of the dateFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateFormat() {
        return dateFormat;
    }

    /**
     * Sets the value of the dateFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateFormat(String value) {
        this.dateFormat = value;
    }

    /**
     * Gets the value of the timeFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeFormat() {
        return timeFormat;
    }

    /**
     * Sets the value of the timeFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeFormat(String value) {
        this.timeFormat = value;
    }

    /**
     * Gets the value of the dateAndTimeFormat property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDateAndTimeFormat() {
        return dateAndTimeFormat;
    }

    /**
     * Sets the value of the dateAndTimeFormat property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDateAndTimeFormat(String value) {
        this.dateAndTimeFormat = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorDetailType }
     *     
     */
    public ErrorDetailType getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorDetailType }
     *     
     */
    public void setError(ErrorDetailType value) {
        this.error = value;
    }

    /**
     * Gets the value of the ownAirlineIdentifier property.
     * 
     */
    public int getOwnAirlineIdentifier() {
        return ownAirlineIdentifier;
    }

    /**
     * Sets the value of the ownAirlineIdentifier property.
     * 
     */
    public void setOwnAirlineIdentifier(int value) {
        this.ownAirlineIdentifier = value;
    }

    /**
     * Gets the value of the defaultOfficeCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDefaultOfficeCode() {
        return defaultOfficeCode;
    }

    /**
     * Sets the value of the defaultOfficeCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDefaultOfficeCode(String value) {
        this.defaultOfficeCode = value;
    }

    /**
     * Gets the value of the airportDateAndTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirportDateAndTime() {
        return airportDateAndTime;
    }

    /**
     * Sets the value of the airportDateAndTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirportDateAndTime(String value) {
        this.airportDateAndTime = value;
    }

    /**
     * Gets the value of the timeZoneInformation property.
     * 
     * @return
     *     possible object is
     *     {@link TimeZoneInformationType }
     *     
     */
    public TimeZoneInformationType getTimeZoneInformation() {
        return timeZoneInformation;
    }

    /**
     * Sets the value of the timeZoneInformation property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeZoneInformationType }
     *     
     */
    public void setTimeZoneInformation(TimeZoneInformationType value) {
        this.timeZoneInformation = value;
    }

    /**
     * Gets the value of the userParameters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the userParameters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getUserParameters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link UserParameterType }
     * 
     * 
     */
    public List<UserParameterType> getUserParameters() {
        if (userParameters == null) {
            userParameters = new ArrayList<UserParameterType>();
        }
        return this.userParameters;
    }

    /**
     * Gets the value of the passwordChangeRequired property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPasswordChangeRequired() {
        return passwordChangeRequired;
    }

    /**
     * Sets the value of the passwordChangeRequired property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPasswordChangeRequired(String value) {
        this.passwordChangeRequired = value;
    }

    /**
     * Gets the value of the portalUserDetails property.
     * 
     * @return
     *     possible object is
     *     {@link PortalUserDetailsType }
     *     
     */
    public PortalUserDetailsType getPortalUserDetails() {
        return portalUserDetails;
    }

    /**
     * Sets the value of the portalUserDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link PortalUserDetailsType }
     *     
     */
    public void setPortalUserDetails(PortalUserDetailsType value) {
        this.portalUserDetails = value;
    }

}
