//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.20 at 04:46:06 PM SGT 
//


package com.ibsplc.icargo.business.admin.accesscontrol.types.standard;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ibsplc.icargo.business.admin.accesscontrol.types.standard package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ibsplc.icargo.business.admin.accesscontrol.types.standard
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link RefDataList }
     * 
     */
    public RefDataList createRefDataList() {
        return new RefDataList();
    }

    /**
     * Create an instance of {@link PortalPrivilegeRequestType }
     * 
     */
    public PortalPrivilegeRequestType createPortalPrivilegeRequestType() {
        return new PortalPrivilegeRequestType();
    }

    /**
     * Create an instance of {@link PortalPrivilegeResponseType }
     * 
     */
    public PortalPrivilegeResponseType createPortalPrivilegeResponseType() {
        return new PortalPrivilegeResponseType();
    }

    /**
     * Create an instance of {@link MobilityLoginRequestType }
     * 
     */
    public MobilityLoginRequestType createMobilityLoginRequestType() {
        return new MobilityLoginRequestType();
    }

    /**
     * Create an instance of {@link PortalUserDetailsType }
     * 
     */
    public PortalUserDetailsType createPortalUserDetailsType() {
        return new PortalUserDetailsType();
    }

    /**
     * Create an instance of {@link AirlineType }
     * 
     */
    public AirlineType createAirlineType() {
        return new AirlineType();
    }

    /**
     * Create an instance of {@link MenuType }
     * 
     */
    public MenuType createMenuType() {
        return new MenuType();
    }

    /**
     * Create an instance of {@link FileDetailsType }
     * 
     */
    public FileDetailsType createFileDetailsType() {
        return new FileDetailsType();
    }

    /**
     * Create an instance of {@link LoginResponseType }
     * 
     */
    public LoginResponseType createLoginResponseType() {
        return new LoginResponseType();
    }

    /**
     * Create an instance of {@link MenuResponseType }
     * 
     */
    public MenuResponseType createMenuResponseType() {
        return new MenuResponseType();
    }

    /**
     * Create an instance of {@link TimeZoneInformationType }
     * 
     */
    public TimeZoneInformationType createTimeZoneInformationType() {
        return new TimeZoneInformationType();
    }

    /**
     * Create an instance of {@link FileStoreInfoType }
     * 
     */
    public FileStoreInfoType createFileStoreInfoType() {
        return new FileStoreInfoType();
    }

    /**
     * Create an instance of {@link CustomerType }
     * 
     */
    public CustomerType createCustomerType() {
        return new CustomerType();
    }

    /**
     * Create an instance of {@link TransferModeDetailsType }
     * 
     */
    public TransferModeDetailsType createTransferModeDetailsType() {
        return new TransferModeDetailsType();
    }

    /**
     * Create an instance of {@link LoginRequestType }
     * 
     */
    public LoginRequestType createLoginRequestType() {
        return new LoginRequestType();
    }

    /**
     * Create an instance of {@link FileStoreDetailsType }
     * 
     */
    public FileStoreDetailsType createFileStoreDetailsType() {
        return new FileStoreDetailsType();
    }

    /**
     * Create an instance of {@link MenuRequestType }
     * 
     */
    public MenuRequestType createMenuRequestType() {
        return new MenuRequestType();
    }

    /**
     * Create an instance of {@link UserParameterType }
     * 
     */
    public UserParameterType createUserParameterType() {
        return new UserParameterType();
    }

    /**
     * Create an instance of {@link ErrorDetailType }
     * 
     */
    public ErrorDetailType createErrorDetailType() {
        return new ErrorDetailType();
    }

    /**
     * Create an instance of {@link FileInfoType }
     * 
     */
    public FileInfoType createFileInfoType() {
        return new FileInfoType();
    }

    /**
     * Create an instance of {@link PrivilegeDataType }
     * 
     */
    public PrivilegeDataType createPrivilegeDataType() {
        return new PrivilegeDataType();
    }

    /**
     * Create an instance of {@link LogoutRequestType }
     * 
     */
    public LogoutRequestType createLogoutRequestType() {
        return new LogoutRequestType();
    }

    /**
     * Create an instance of {@link MobilityLoginResponseType }
     * 
     */
    public MobilityLoginResponseType createMobilityLoginResponseType() {
        return new MobilityLoginResponseType();
    }

    /**
     * Create an instance of {@link LogoutResponseType }
     * 
     */
    public LogoutResponseType createLogoutResponseType() {
        return new LogoutResponseType();
    }

    /**
     * Create an instance of {@link RefDataList.Entry }
     * 
     */
    public RefDataList.Entry createRefDataListEntry() {
        return new RefDataList.Entry();
    }

}
