//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.20 at 04:46:06 PM SGT 
//


package com.ibsplc.icargo.business.admin.accesscontrol.types.standard;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for portalUserDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="portalUserDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="portalUserType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="maxNumberOfChildUsers" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="numberOfChildUsers" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="userTitle" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userFirstName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="portalDefaultRoleGroup" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="airlineCodes" type="{http://www.ibsplc.com/icargo/services/types/AdminAccessControlService/standard/2012/12/12_01}airlineType" minOccurs="0"/>
 *         &lt;element name="customerDetails" type="{http://www.ibsplc.com/icargo/services/types/AdminAccessControlService/standard/2012/12/12_01}customerType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "portalUserDetailsType", propOrder = {
    "portalUserType",
    "maxNumberOfChildUsers",
    "numberOfChildUsers",
    "userTitle",
    "userFirstName",
    "portalDefaultRoleGroup",
    "airlineCodes",
    "customerDetails"
})
public class PortalUserDetailsType {

    protected String portalUserType;
    protected Integer maxNumberOfChildUsers;
    protected Integer numberOfChildUsers;
    protected String userTitle;
    protected String userFirstName;
    protected String portalDefaultRoleGroup;
    protected AirlineType airlineCodes;
    protected CustomerType customerDetails;

    /**
     * Gets the value of the portalUserType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortalUserType() {
        return portalUserType;
    }

    /**
     * Sets the value of the portalUserType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortalUserType(String value) {
        this.portalUserType = value;
    }

    /**
     * Gets the value of the maxNumberOfChildUsers property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxNumberOfChildUsers() {
        return maxNumberOfChildUsers;
    }

    /**
     * Sets the value of the maxNumberOfChildUsers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxNumberOfChildUsers(Integer value) {
        this.maxNumberOfChildUsers = value;
    }

    /**
     * Gets the value of the numberOfChildUsers property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getNumberOfChildUsers() {
        return numberOfChildUsers;
    }

    /**
     * Sets the value of the numberOfChildUsers property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setNumberOfChildUsers(Integer value) {
        this.numberOfChildUsers = value;
    }

    /**
     * Gets the value of the userTitle property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserTitle() {
        return userTitle;
    }

    /**
     * Sets the value of the userTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserTitle(String value) {
        this.userTitle = value;
    }

    /**
     * Gets the value of the userFirstName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserFirstName() {
        return userFirstName;
    }

    /**
     * Sets the value of the userFirstName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserFirstName(String value) {
        this.userFirstName = value;
    }

    /**
     * Gets the value of the portalDefaultRoleGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPortalDefaultRoleGroup() {
        return portalDefaultRoleGroup;
    }

    /**
     * Sets the value of the portalDefaultRoleGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPortalDefaultRoleGroup(String value) {
        this.portalDefaultRoleGroup = value;
    }

    /**
     * Gets the value of the airlineCodes property.
     * 
     * @return
     *     possible object is
     *     {@link AirlineType }
     *     
     */
    public AirlineType getAirlineCodes() {
        return airlineCodes;
    }

    /**
     * Sets the value of the airlineCodes property.
     * 
     * @param value
     *     allowed object is
     *     {@link AirlineType }
     *     
     */
    public void setAirlineCodes(AirlineType value) {
        this.airlineCodes = value;
    }

    /**
     * Gets the value of the customerDetails property.
     * 
     * @return
     *     possible object is
     *     {@link CustomerType }
     *     
     */
    public CustomerType getCustomerDetails() {
        return customerDetails;
    }

    /**
     * Sets the value of the customerDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link CustomerType }
     *     
     */
    public void setCustomerDetails(CustomerType value) {
        this.customerDetails = value;
    }

}
