//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.20 at 04:46:06 PM SGT 
//


package com.ibsplc.icargo.business.admin.accesscontrol.types.standard;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TimeZoneInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="TimeZoneInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="timeZoneName" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="bias" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="daylightBias" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="daylightDay" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="daylightDayOfWeek" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="daylightHour" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="daylightMilliseconds" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="daylightMinute" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="daylightMonth" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="daylightSecond" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="daylightYear" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="standardBias" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="standardDay" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="standardDayOfWeek" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="standardHour" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="standardMilliseconds" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="standardMinute" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="standardMonth" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="standardSecond" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *         &lt;element name="standardYear" type="{http://www.w3.org/2001/XMLSchema}int"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TimeZoneInformationType", propOrder = {
    "timeZoneName",
    "bias",
    "daylightBias",
    "daylightDay",
    "daylightDayOfWeek",
    "daylightHour",
    "daylightMilliseconds",
    "daylightMinute",
    "daylightMonth",
    "daylightSecond",
    "daylightYear",
    "standardBias",
    "standardDay",
    "standardDayOfWeek",
    "standardHour",
    "standardMilliseconds",
    "standardMinute",
    "standardMonth",
    "standardSecond",
    "standardYear"
})
public class TimeZoneInformationType {

    protected String timeZoneName;
    protected int bias;
    protected int daylightBias;
    protected int daylightDay;
    protected int daylightDayOfWeek;
    protected int daylightHour;
    protected int daylightMilliseconds;
    protected int daylightMinute;
    protected int daylightMonth;
    protected int daylightSecond;
    protected int daylightYear;
    protected int standardBias;
    protected int standardDay;
    protected int standardDayOfWeek;
    protected int standardHour;
    protected int standardMilliseconds;
    protected int standardMinute;
    protected int standardMonth;
    protected int standardSecond;
    protected int standardYear;

    /**
     * Gets the value of the timeZoneName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTimeZoneName() {
        return timeZoneName;
    }

    /**
     * Sets the value of the timeZoneName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTimeZoneName(String value) {
        this.timeZoneName = value;
    }

    /**
     * Gets the value of the bias property.
     * 
     */
    public int getBias() {
        return bias;
    }

    /**
     * Sets the value of the bias property.
     * 
     */
    public void setBias(int value) {
        this.bias = value;
    }

    /**
     * Gets the value of the daylightBias property.
     * 
     */
    public int getDaylightBias() {
        return daylightBias;
    }

    /**
     * Sets the value of the daylightBias property.
     * 
     */
    public void setDaylightBias(int value) {
        this.daylightBias = value;
    }

    /**
     * Gets the value of the daylightDay property.
     * 
     */
    public int getDaylightDay() {
        return daylightDay;
    }

    /**
     * Sets the value of the daylightDay property.
     * 
     */
    public void setDaylightDay(int value) {
        this.daylightDay = value;
    }

    /**
     * Gets the value of the daylightDayOfWeek property.
     * 
     */
    public int getDaylightDayOfWeek() {
        return daylightDayOfWeek;
    }

    /**
     * Sets the value of the daylightDayOfWeek property.
     * 
     */
    public void setDaylightDayOfWeek(int value) {
        this.daylightDayOfWeek = value;
    }

    /**
     * Gets the value of the daylightHour property.
     * 
     */
    public int getDaylightHour() {
        return daylightHour;
    }

    /**
     * Sets the value of the daylightHour property.
     * 
     */
    public void setDaylightHour(int value) {
        this.daylightHour = value;
    }

    /**
     * Gets the value of the daylightMilliseconds property.
     * 
     */
    public int getDaylightMilliseconds() {
        return daylightMilliseconds;
    }

    /**
     * Sets the value of the daylightMilliseconds property.
     * 
     */
    public void setDaylightMilliseconds(int value) {
        this.daylightMilliseconds = value;
    }

    /**
     * Gets the value of the daylightMinute property.
     * 
     */
    public int getDaylightMinute() {
        return daylightMinute;
    }

    /**
     * Sets the value of the daylightMinute property.
     * 
     */
    public void setDaylightMinute(int value) {
        this.daylightMinute = value;
    }

    /**
     * Gets the value of the daylightMonth property.
     * 
     */
    public int getDaylightMonth() {
        return daylightMonth;
    }

    /**
     * Sets the value of the daylightMonth property.
     * 
     */
    public void setDaylightMonth(int value) {
        this.daylightMonth = value;
    }

    /**
     * Gets the value of the daylightSecond property.
     * 
     */
    public int getDaylightSecond() {
        return daylightSecond;
    }

    /**
     * Sets the value of the daylightSecond property.
     * 
     */
    public void setDaylightSecond(int value) {
        this.daylightSecond = value;
    }

    /**
     * Gets the value of the daylightYear property.
     * 
     */
    public int getDaylightYear() {
        return daylightYear;
    }

    /**
     * Sets the value of the daylightYear property.
     * 
     */
    public void setDaylightYear(int value) {
        this.daylightYear = value;
    }

    /**
     * Gets the value of the standardBias property.
     * 
     */
    public int getStandardBias() {
        return standardBias;
    }

    /**
     * Sets the value of the standardBias property.
     * 
     */
    public void setStandardBias(int value) {
        this.standardBias = value;
    }

    /**
     * Gets the value of the standardDay property.
     * 
     */
    public int getStandardDay() {
        return standardDay;
    }

    /**
     * Sets the value of the standardDay property.
     * 
     */
    public void setStandardDay(int value) {
        this.standardDay = value;
    }

    /**
     * Gets the value of the standardDayOfWeek property.
     * 
     */
    public int getStandardDayOfWeek() {
        return standardDayOfWeek;
    }

    /**
     * Sets the value of the standardDayOfWeek property.
     * 
     */
    public void setStandardDayOfWeek(int value) {
        this.standardDayOfWeek = value;
    }

    /**
     * Gets the value of the standardHour property.
     * 
     */
    public int getStandardHour() {
        return standardHour;
    }

    /**
     * Sets the value of the standardHour property.
     * 
     */
    public void setStandardHour(int value) {
        this.standardHour = value;
    }

    /**
     * Gets the value of the standardMilliseconds property.
     * 
     */
    public int getStandardMilliseconds() {
        return standardMilliseconds;
    }

    /**
     * Sets the value of the standardMilliseconds property.
     * 
     */
    public void setStandardMilliseconds(int value) {
        this.standardMilliseconds = value;
    }

    /**
     * Gets the value of the standardMinute property.
     * 
     */
    public int getStandardMinute() {
        return standardMinute;
    }

    /**
     * Sets the value of the standardMinute property.
     * 
     */
    public void setStandardMinute(int value) {
        this.standardMinute = value;
    }

    /**
     * Gets the value of the standardMonth property.
     * 
     */
    public int getStandardMonth() {
        return standardMonth;
    }

    /**
     * Sets the value of the standardMonth property.
     * 
     */
    public void setStandardMonth(int value) {
        this.standardMonth = value;
    }

    /**
     * Gets the value of the standardSecond property.
     * 
     */
    public int getStandardSecond() {
        return standardSecond;
    }

    /**
     * Sets the value of the standardSecond property.
     * 
     */
    public void setStandardSecond(int value) {
        this.standardSecond = value;
    }

    /**
     * Gets the value of the standardYear property.
     * 
     */
    public int getStandardYear() {
        return standardYear;
    }

    /**
     * Sets the value of the standardYear property.
     * 
     */
    public void setStandardYear(int value) {
        this.standardYear = value;
    }

}
