//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.20 at 04:46:06 PM SGT 
//


package com.ibsplc.icargo.business.admin.accesscontrol.types.standard;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for transferModeDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="transferModeDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="transferMode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parameterOne" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parameterTwo" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parameterThree" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parameterFour" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="parameterFive" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "transferModeDetailsType", propOrder = {
    "transferMode",
    "parameterOne",
    "parameterTwo",
    "parameterThree",
    "parameterFour",
    "parameterFive"
})
public class TransferModeDetailsType {

    @XmlElement(required = true)
    protected String transferMode;
    @XmlElement(required = true)
    protected String parameterOne;
    @XmlElement(required = true)
    protected String parameterTwo;
    @XmlElement(required = true)
    protected String parameterThree;
    @XmlElement(required = true)
    protected String parameterFour;
    @XmlElement(required = true)
    protected String parameterFive;

    /**
     * Gets the value of the transferMode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTransferMode() {
        return transferMode;
    }

    /**
     * Sets the value of the transferMode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTransferMode(String value) {
        this.transferMode = value;
    }

    /**
     * Gets the value of the parameterOne property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParameterOne() {
        return parameterOne;
    }

    /**
     * Sets the value of the parameterOne property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParameterOne(String value) {
        this.parameterOne = value;
    }

    /**
     * Gets the value of the parameterTwo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParameterTwo() {
        return parameterTwo;
    }

    /**
     * Sets the value of the parameterTwo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParameterTwo(String value) {
        this.parameterTwo = value;
    }

    /**
     * Gets the value of the parameterThree property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParameterThree() {
        return parameterThree;
    }

    /**
     * Sets the value of the parameterThree property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParameterThree(String value) {
        this.parameterThree = value;
    }

    /**
     * Gets the value of the parameterFour property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParameterFour() {
        return parameterFour;
    }

    /**
     * Sets the value of the parameterFour property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParameterFour(String value) {
        this.parameterFour = value;
    }

    /**
     * Gets the value of the parameterFive property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParameterFive() {
        return parameterFive;
    }

    /**
     * Sets the value of the parameterFive property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParameterFive(String value) {
        this.parameterFive = value;
    }

}
