
package com.ibsplc.icargo.services.mailtrackingdefaultsservice.standard._2012._12._12_01;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InvalidRequestFault", targetNamespace = "http://www.ibsplc.com/icargo/services/MailTrackingDefaultsService/standard/2012/12/12_01")
public class InvalidRequestFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidRequestFaultDetail faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public InvalidRequestFault(String message, InvalidRequestFaultDetail faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public InvalidRequestFault(String message, InvalidRequestFaultDetail faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.ibsplc.icargo.services.mailtrackingdefaultsservice.standard._2012._12._12_01.InvalidRequestFaultDetail
     */
    public InvalidRequestFaultDetail getFaultInfo() {
        return faultInfo;
    }

}
