
package com.ibsplc.icargo.services.mailtrackingdefaultsservice.standard._2012._12._12_01;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "MailTrackingDefaultsService", targetNamespace = "http://www.ibsplc.com/icargo/services/MailTrackingDefaultsService/standard/2012/12/12_01", wsdlLocation = "file:/C:/Users/rumani.5.jain/Downloads/wsdl/WSDLForSATS/WSDLForSATS/wsdl/mailtracking/defaults/standard/MailTrackingDefaultsService.wsdl")
public class MailTrackingDefaultsService_Service
    extends Service
{

    private final static URL MAILTRACKINGDEFAULTSSERVICE_WSDL_LOCATION;
    private final static WebServiceException MAILTRACKINGDEFAULTSSERVICE_EXCEPTION;
    private final static QName MAILTRACKINGDEFAULTSSERVICE_QNAME = new QName("http://www.ibsplc.com/icargo/services/MailTrackingDefaultsService/standard/2012/12/12_01", "MailTrackingDefaultsService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/rumani.5.jain/Downloads/wsdl/WSDLForSATS/WSDLForSATS/wsdl/mailtracking/defaults/standard/MailTrackingDefaultsService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        MAILTRACKINGDEFAULTSSERVICE_WSDL_LOCATION = url;
        MAILTRACKINGDEFAULTSSERVICE_EXCEPTION = e;
    }

    public MailTrackingDefaultsService_Service() {
        super(__getWsdlLocation(), MAILTRACKINGDEFAULTSSERVICE_QNAME);
    }

    public MailTrackingDefaultsService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), MAILTRACKINGDEFAULTSSERVICE_QNAME, features);
    }

    public MailTrackingDefaultsService_Service(URL wsdlLocation) {
        super(wsdlLocation, MAILTRACKINGDEFAULTSSERVICE_QNAME);
    }

    public MailTrackingDefaultsService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, MAILTRACKINGDEFAULTSSERVICE_QNAME, features);
    }

    public MailTrackingDefaultsService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public MailTrackingDefaultsService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns MailTrackingDefaultsService
     */
    @WebEndpoint(name = "MailTrackingDefaultsService")
    public MailTrackingDefaultsService getMailTrackingDefaultsService() {
        return super.getPort(new QName("http://www.ibsplc.com/icargo/services/MailTrackingDefaultsService/standard/2012/12/12_01", "MailTrackingDefaultsService"), MailTrackingDefaultsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MailTrackingDefaultsService
     */
    @WebEndpoint(name = "MailTrackingDefaultsService")
    public MailTrackingDefaultsService getMailTrackingDefaultsService(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ibsplc.com/icargo/services/MailTrackingDefaultsService/standard/2012/12/12_01", "MailTrackingDefaultsService"), MailTrackingDefaultsService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (MAILTRACKINGDEFAULTSSERVICE_EXCEPTION!= null) {
            throw MAILTRACKINGDEFAULTSSERVICE_EXCEPTION;
        }
        return MAILTRACKINGDEFAULTSSERVICE_WSDL_LOCATION;
    }

}
