
package com.ibsplc.icargo.services.mailtrackingdefaultsservice.standard._2012._12._12_01;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import com.ibsplc.icargo.business.mailtracking.defaults.types.standard.SaveMailDetailsRequestType;
import com.ibsplc.icargo.business.mailtracking.defaults.types.standard.SaveMailDetailsResponseType;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "MailTrackingDefaultsService", targetNamespace = "http://www.ibsplc.com/icargo/services/MailTrackingDefaultsService/standard/2012/12/12_01")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    com.ibsplc.icargo.business.mailtracking.defaults.types.standard.ObjectFactory.class,
    com.ibsplc.icargo.business.shared.defaults.types.standard.ObjectFactory.class,
    com.ibsplc.icargo.framework.services.jaxws.types.common.ObjectFactory.class,
    com.ibsplc.icargo.services.mailtrackingdefaultsservice.standard._2012._12._12_01.ObjectFactory.class
})
public interface MailTrackingDefaultsService {


    /**
     * 
     * @param parameters
     * @return
     *     returns com.ibsplc.icargo.business.mailtracking.defaults.types.standard.SaveMailDetailsResponseType
     * @throws InvalidRequestFault
     * @throws ServiceFault
     */
    @WebMethod(action = "http://www.ibsplc.com/icargo/services/MailTrackingService#saveMailBagDetails")
    @WebResult(name = "saveMailDetailsGHAResponse", targetNamespace = "http://www.ibsplc.com/icargo/services/MailTrackingDefaultsService/standard/2012/12/12_01", partName = "parameters")
    public SaveMailDetailsResponseType saveMailBagDetails(
        @WebParam(name = "saveMailDetailsRequest", targetNamespace = "http://www.ibsplc.com/icargo/services/MailTrackingDefaultsService/standard/2012/12/12_01", partName = "parameters")
        SaveMailDetailsRequestType parameters)
        throws InvalidRequestFault, ServiceFault
    ;

}
