//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.20 at 10:45:55 AM IST 
//


package com.ibsplc.icargo.services.mailtrackingdefaultsservice.standard._2012._12._12_01;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;
import com.ibsplc.icargo.business.mailtracking.defaults.types.standard.SaveMailDetailsRequestType;
import com.ibsplc.icargo.business.mailtracking.defaults.types.standard.SaveMailDetailsResponseType;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ibsplc.icargo.services.mailtrackingdefaultsservice.standard._2012._12._12_01 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _SaveMailDetailsRequest_QNAME = new QName("http://www.ibsplc.com/icargo/services/MailTrackingDefaultsService/standard/2012/12/12_01", "saveMailDetailsRequest");
    private final static QName _SaveMailDetailsGHAResponse_QNAME = new QName("http://www.ibsplc.com/icargo/services/MailTrackingDefaultsService/standard/2012/12/12_01", "saveMailDetailsGHAResponse");
    private final static QName _ServiceFault_QNAME = new QName("http://www.ibsplc.com/icargo/services/MailTrackingDefaultsService/standard/2012/12/12_01", "ServiceFault");
    private final static QName _InvalidRequestFault_QNAME = new QName("http://www.ibsplc.com/icargo/services/MailTrackingDefaultsService/standard/2012/12/12_01", "InvalidRequestFault");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ibsplc.icargo.services.mailtrackingdefaultsservice.standard._2012._12._12_01
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link InvalidRequestFaultDetail }
     * 
     */
    public InvalidRequestFaultDetail createInvalidRequestFaultDetail() {
        return new InvalidRequestFaultDetail();
    }

    /**
     * Create an instance of {@link ServiceFaultDetail }
     * 
     */
    public ServiceFaultDetail createServiceFaultDetail() {
        return new ServiceFaultDetail();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SaveMailDetailsRequestType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibsplc.com/icargo/services/MailTrackingDefaultsService/standard/2012/12/12_01", name = "saveMailDetailsRequest")
    public JAXBElement<SaveMailDetailsRequestType> createSaveMailDetailsRequest(SaveMailDetailsRequestType value) {
        return new JAXBElement<SaveMailDetailsRequestType>(_SaveMailDetailsRequest_QNAME, SaveMailDetailsRequestType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link SaveMailDetailsResponseType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibsplc.com/icargo/services/MailTrackingDefaultsService/standard/2012/12/12_01", name = "saveMailDetailsGHAResponse")
    public JAXBElement<SaveMailDetailsResponseType> createSaveMailDetailsGHAResponse(SaveMailDetailsResponseType value) {
        return new JAXBElement<SaveMailDetailsResponseType>(_SaveMailDetailsGHAResponse_QNAME, SaveMailDetailsResponseType.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ServiceFaultDetail }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibsplc.com/icargo/services/MailTrackingDefaultsService/standard/2012/12/12_01", name = "ServiceFault")
    public JAXBElement<ServiceFaultDetail> createServiceFault(ServiceFaultDetail value) {
        return new JAXBElement<ServiceFaultDetail>(_ServiceFault_QNAME, ServiceFaultDetail.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InvalidRequestFaultDetail }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.ibsplc.com/icargo/services/MailTrackingDefaultsService/standard/2012/12/12_01", name = "InvalidRequestFault")
    public JAXBElement<InvalidRequestFaultDetail> createInvalidRequestFault(InvalidRequestFaultDetail value) {
        return new JAXBElement<InvalidRequestFaultDetail>(_InvalidRequestFault_QNAME, InvalidRequestFaultDetail.class, null, value);
    }

}
