//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2018.06.20 at 10:45:55 AM IST 
//


package com.ngen.cosys.AirmailStatus.Model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;

import org.springframework.stereotype.Component;


/**
 * <p>Java class for MailDetailsRequestType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MailDetailsRequestType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="product" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="scanType" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="carrierCode" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="flightNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="flightDate" type="{http://www.ibsplc.com/icargo/services/types/SharedDefaultService/ICargoCommon/standard/2012/12/12_01}Date" minOccurs="0"/>
 *         &lt;element name="containerPou" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="containerNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="containerType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="containerDestination" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="containerPol" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="Remarks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="mailTag" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="damageCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="damageRemarks" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="offloadReason" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="returnCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="toContainerType" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="toContainer" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="toCarrierCode" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="toFlightNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="toFlightDate" type="{http://www.ibsplc.com/icargo/services/types/SharedDefaultService/ICargoCommon/standard/2012/12/12_01}Date" minOccurs="0"/>
 *         &lt;element name="toContainerPOU" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="toContainerDestination" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="consignmentDocumentNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="serialNumber" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="isPABuilt" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="isDelivered" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="userName" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="scanDateTime" type="{http://www.ibsplc.com/icargo/services/types/SharedDefaultService/ICargoCommon/standard/2012/12/12_01}dateTime"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MailDetailsRequestType", propOrder = {
    "product",
    "scanType",
    "carrierCode",
    "flightNumber",
    "flightDate",
    "containerPou",
    "containerNumber",
    "containerType",
    "containerDestination",
    "containerPol",
    "remarks",
    "mailTag",
    "damageCode",
    "damageRemarks",
    "offloadReason",
    "returnCode",
    "toContainerType",
    "toContainer",
    "toCarrierCode",
    "toFlightNumber",
    "toFlightDate",
    "toContainerPOU",
    "toContainerDestination",
    "consignmentDocumentNumber",
    "serialNumber",
    "isPABuilt",
    "isDelivered",
    "userName",
    "scanDateTime"
})
@XmlRootElement(name = "MailDetailsRequestType")
@Component
public class MailDetailsRequestType {

    @XmlElement(required = true)
    protected String product;
    @XmlElement(required = true)
    protected String scanType;
    @XmlElement(required = true)
    protected String carrierCode;
    protected String flightNumber;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String flightDate;
    protected String containerPou;
    protected String containerNumber;
    protected String containerType;
    protected String containerDestination;
    protected String containerPol;
    @XmlElement(name = "Remarks")
    protected String remarks;
    protected String mailTag;
    protected String damageCode;
    protected String damageRemarks;
    protected String offloadReason;
    protected String returnCode;
    protected String toContainerType;
    protected String toContainer;
    protected String toCarrierCode;
    protected String toFlightNumber;
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String toFlightDate;
    protected String toContainerPOU;
    protected String toContainerDestination;
    protected String consignmentDocumentNumber;
    @XmlElement(required = true)
    protected String serialNumber;
    protected String isPABuilt;
    protected String isDelivered;
    @XmlElement(required = true)
    protected String userName;
    @XmlElement(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    @XmlSchemaType(name = "token")
    protected String scanDateTime;

   /**
     * Gets the value of the product property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getProduct() {
        return product;
    }

    /**
     * Sets the value of the product property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setProduct(String value) {
        this.product = value;
    }

    /**
     * Gets the value of the scanType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScanType() {
        return scanType;
    }

    /**
     * Sets the value of the scanType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScanType(String value) {
        this.scanType = value;
    }

    /**
     * Gets the value of the carrierCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getCarrierCode() {
        return carrierCode;
    }

    /**
     * Sets the value of the carrierCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setCarrierCode(String value) {
        this.carrierCode = value;
    }

    /**
     * Gets the value of the flightNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlightNumber() {
        return flightNumber;
    }

    /**
     * Sets the value of the flightNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlightNumber(String value) {
        this.flightNumber = value;
    }

    /**
     * Gets the value of the flightDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlightDate() {
        return flightDate;
    }

    /**
     * Sets the value of the flightDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlightDate(String value) {
        this.flightDate = value;
    }

    /**
     * Gets the value of the containerPou property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainerPou() {
        return containerPou;
    }

    /**
     * Sets the value of the containerPou property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainerPou(String value) {
        this.containerPou = value;
    }

    /**
     * Gets the value of the containerNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainerNumber() {
        return containerNumber;
    }

    /**
     * Sets the value of the containerNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainerNumber(String value) {
        this.containerNumber = value;
    }

    /**
     * Gets the value of the containerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainerType() {
        return containerType;
    }

    /**
     * Sets the value of the containerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainerType(String value) {
        this.containerType = value;
    }

    /**
     * Gets the value of the containerDestination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainerDestination() {
        return containerDestination;
    }

    /**
     * Sets the value of the containerDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainerDestination(String value) {
        this.containerDestination = value;
    }

    /**
     * Gets the value of the containerPol property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContainerPol() {
        return containerPol;
    }

    /**
     * Sets the value of the containerPol property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContainerPol(String value) {
        this.containerPol = value;
    }

    /**
     * Gets the value of the remarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * Sets the value of the remarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRemarks(String value) {
        this.remarks = value;
    }

    /**
     * Gets the value of the mailTag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMailTag() {
        return mailTag;
    }

    /**
     * Sets the value of the mailTag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMailTag(String value) {
        this.mailTag = value;
    }

    /**
     * Gets the value of the damageCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDamageCode() {
        return damageCode;
    }

    /**
     * Sets the value of the damageCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDamageCode(String value) {
        this.damageCode = value;
    }

    /**
     * Gets the value of the damageRemarks property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDamageRemarks() {
        return damageRemarks;
    }

    /**
     * Sets the value of the damageRemarks property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDamageRemarks(String value) {
        this.damageRemarks = value;
    }

    /**
     * Gets the value of the offloadReason property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOffloadReason() {
        return offloadReason;
    }

    /**
     * Sets the value of the offloadReason property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOffloadReason(String value) {
        this.offloadReason = value;
    }

    /**
     * Gets the value of the returnCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getReturnCode() {
        return returnCode;
    }

    /**
     * Sets the value of the returnCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setReturnCode(String value) {
        this.returnCode = value;
    }

    /**
     * Gets the value of the toContainerType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToContainerType() {
        return toContainerType;
    }

    /**
     * Sets the value of the toContainerType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToContainerType(String value) {
        this.toContainerType = value;
    }

    /**
     * Gets the value of the toContainer property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToContainer() {
        return toContainer;
    }

    /**
     * Sets the value of the toContainer property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToContainer(String value) {
        this.toContainer = value;
    }

    /**
     * Gets the value of the toCarrierCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToCarrierCode() {
        return toCarrierCode;
    }

    /**
     * Sets the value of the toCarrierCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToCarrierCode(String value) {
        this.toCarrierCode = value;
    }

    /**
     * Gets the value of the toFlightNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToFlightNumber() {
        return toFlightNumber;
    }

    /**
     * Sets the value of the toFlightNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToFlightNumber(String value) {
        this.toFlightNumber = value;
    }

    /**
     * Gets the value of the toFlightDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToFlightDate() {
        return toFlightDate;
    }

    /**
     * Sets the value of the toFlightDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToFlightDate(String value) {
        this.toFlightDate = value;
    }

    /**
     * Gets the value of the toContainerPOU property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToContainerPOU() {
        return toContainerPOU;
    }

    /**
     * Sets the value of the toContainerPOU property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToContainerPOU(String value) {
        this.toContainerPOU = value;
    }

    /**
     * Gets the value of the toContainerDestination property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getToContainerDestination() {
        return toContainerDestination;
    }

    /**
     * Sets the value of the toContainerDestination property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setToContainerDestination(String value) {
        this.toContainerDestination = value;
    }

    /**
     * Gets the value of the consignmentDocumentNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getConsignmentDocumentNumber() {
        return consignmentDocumentNumber;
    }

    /**
     * Sets the value of the consignmentDocumentNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setConsignmentDocumentNumber(String value) {
        this.consignmentDocumentNumber = value;
    }

    /**
     * Gets the value of the serialNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSerialNumber() {
        return serialNumber;
    }

    /**
     * Sets the value of the serialNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSerialNumber(String value) {
        this.serialNumber = value;
    }

    /**
     * Gets the value of the isPABuilt property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsPABuilt() {
        return isPABuilt;
    }

    /**
     * Sets the value of the isPABuilt property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsPABuilt(String value) {
        this.isPABuilt = value;
    }

    /**
     * Gets the value of the isDelivered property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIsDelivered() {
        return isDelivered;
    }

    /**
     * Sets the value of the isDelivered property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIsDelivered(String value) {
        this.isDelivered = value;
    }

    /**
     * Gets the value of the userName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUserName() {
        return userName;
    }

    /**
     * Sets the value of the userName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUserName(String value) {
        this.userName = value;
    }

    /**
     * Gets the value of the scanDateTime property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getScanDateTime() {
        return scanDateTime;
    }

    /**
     * Sets the value of the scanDateTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setScanDateTime(String value) {
        this.scanDateTime = value;
    }

}
