-- Display Incoming Flight --

DROP TABLE Flt_OperativeFlight_Segments IF EXISTS;

DROP TABLE Imp_FlightEvents IF EXISTS;

DROP TABLE Flt_OperativeFlight_Legs IF EXISTS;

DROP TABLE Flt_OperativeFlight IF EXISTS;

DROP TABLE Transhipment_ThroughTransitWorkingList IF EXISTS;

CREATE TABLE Flt_OperativeFlight (
	 Flight_ID  integer,
	 CarrierCode  varchar(3) ,
	 FlightNumber  varchar(5) ,
	 FlightKey  varchar(8) ,
	 FlightOriginDate  datetime ,
	 ExtraFlightFlag  integer ,
	 FlightCreation  varchar(3) ,
	 FlightCancelFlag  varchar(1) ,
	 FlightScheduleChange  integer,
	 ChangedByASM  integer,
	 FlightStatus  varchar(3) ,
	 AirlineLoadingInstruction  integer,
	 FlightOperationPalletsQty  integer,
	 FlightOperationContainerQty  integer,
	 CargoPalletsQty  integer,
	 CargoContainerQty  integer,
	 TransitPalletsQty  integer ,
	 TransitContainerQty  integer ,
	 WeightUnit  varchar(1) ,
	 JointFlightFlag  integer ,
	 ApronFlag  integer ,
	 ApronDate  datetime ,
	 FlightRestoredFlag  integer ,
	 CountSentToApron  integer ,
	 FlightDepDate  datetime ,
	 ParkingBayArrivalAircraft  varchar(4) ,
	 ParkingBayDepAircraft  varchar(4) ,
	 FlightServiceType  varchar(1) ,
	 InboundFlightDelayFlag  integer ,
	 InboundFlightDelayReason  varchar(65) ,
	 OutboundFlightDelayFlag  integer ,
	 OutboundFlightDelayReason  varchar(65) ,
	 MaxULDCount  integer ,
	 InboundAircraftRegNo  varchar(10) ,
	 OutboundAircraftRegNo  varchar(10) ,
	 DateSTD  datetime ,
	 DateSTA  datetime ,
	 FlightType  varchar(1) ,
	 GroundHandlerCode  varchar(32) ,
	 FlightAutoCompleteFlag  integer(1) ,
	 CreatedUser_Code  varchar(64) ,
	 Created_DateTime  datetime ,
	 LastUpdatedUser_Code  varchar(64) ,
	 LastUpdated_DateTime  datetime );

CREATE TABLE Flt_OperativeFlight_Segments (
	 Flight_ID  varchar(15),
	 FlightBoardPoint  varchar(3),
	 FlightOffPoint  varchar(3),
	 FlightSegmentOrder  varchar(4),
	 DateSTD  datetime ,
	 DateSTA  datetime ,
	 SegmentLegFlag  varchar(1) ,
	 NoFreightLoading  varchar(1) ,
	 FlightTechnicalStopFlag  varchar(1) ,
	 NoCargoFlag  varchar(1) ,
	 NoMailFlag  varchar(1) ,
	 FFM_ReceivedFlag  varchar(1) ,
	 ArrivalManifestUser_Code  varchar(64) ,
	 ArrivalManifestDate  datetime ,
	 SegmentFinalized  varchar(1) ,
	 DateFFM  datetime ,
	 FFM_RejectCount  varchar(2) ,
	 FFM_AcceptCount  varchar(2) ,
	 DomesticFlightFlag  varchar(1) ,
	 CreatedUser_Code  varchar(64) ,
	 Created_DateTime  datetime ,
	 LastUpdatedUser_Code  varchar(64) ,
	 LastUpdated_DateTime  datetime ,
	 FlightSegmentId  varchar(15) );

CREATE TABLE Flt_OperativeFlight_Legs (
	 Flight_ID  integer ,
	 FlightBoardPoint  varchar(3) ,
	 FlightOffPoint  varchar(3) ,
	 FlightSegmentOrder  integer ,
	 DateSTD  datetime,
	 DateSTA  datetime,
	 DateETD  datetime ,
	 DateETA  datetime ,
	 DateATD  datetime ,
	 DateATA  datetime ,
	 DomesticFlightFlag  integer ,
	 AircraftRegCode  varchar(10) ,
	 AircraftType  varchar(3) ,
	 CreatedUser_Code  varchar(64) ,
	 Created_DateTime  datetime ,
	 LastUpdatedUser_Code  varchar(64) ,
	 LastUpdated_DateTime  datetime );
	 
CREATE TABLE Imp_FlightEvents (
	 ImpFlightEventsId  varchar(15) ,
	 FlightId  varchar(15) ,
	 FirstULDTowedBy  varchar(64) ,
	 FirstULDTowedAt  datetime ,
	 LastULDTowedBy  varchar(64) ,
	 LastULDTowedAt  datetime ,
	 InboundULDListFinalizedBy  varchar(64) ,
	 InboundULDListFinalizedAt  datetime ,
	 FirstULDCheckedInAt  datetime ,
	 FirstULDCheckedInBy  varchar(64) ,
	 FirstTimeRampCheckInCompletedAt  datetime ,
	 FirstTimeRampCheckInCompletedBy  varchar(64) ,
	 RampCheckInCompletedAt  datetime ,
	 RampCheckInCompletedBy  varchar(64) ,
	 FirstTimeDocumentVerificationCompletedAt  datetime ,
	 FirstTimeDocumentVerificationCompletedBy  varchar(64) ,
	 DocumentVerificationCompletedAt  datetime ,
	 DocumentVerificationCompletedBy  varchar(64) ,
	 FirstTimeBreakDownCompletedAt  datetime ,
	 FirstTimeBreakDownCompletedBy  varchar(64) ,
	 BreakDownCompletedAt  datetime ,
	 BreakDownCompletedBy  varchar(64) ,
	 InwardServiceReportFinalizedAt  datetime ,
	 InwardServiceReportFinalizedBy  varchar(64) ,
	 FirstTimeFlightCompletedAt  datetime ,
	 FirstTimeFlightCompletedBy  varchar(64) ,
	 FlightCompletedAt  datetime ,
	 FlightCompletedBy  varchar(64) ,
	 FirstTimeFlightClosedBy  varchar(64) ,
	 FirstTimeFightClosedAt  datetime ,
	 FlightClosedBy  varchar(64) ,
	 FightClosedAt  datetime ,
	 ThroughTransitWorkingListFinalizedAt  datetime ,
	 ThroughTransitWorkingListFinalizedBy  varchar(64) ,
	 CreatedUserCode  varchar(64) ,
	 CreatedDateTime  datetime ,
	 LastUpdatedUserCode  varchar(64) ,
	 LastUpdatedDateTime  datetime ,
	 FlightDiscrepncyListSentBy  varchar(64) ,
	 FlightDiscrepncyListSentAt  datetime,
	 ShortTransitBulkShipmentExists bit
	 );
	 
CREATE TABLE Transhipment_ThroughTransitWorkingList(
	TransThroughTransitWorkingListId varchar(64),
	InboundFlightId varchar(15),
	OutboundFlightId varchar(15),
	FinalizedFlag bit,
	FinalizedBy varchar(64),
	FinalizedDate datetime,
	CreatedUserCode varchar(64),
	CreatedDateTime datetime,
	LastUpdatedUserCode varchar(64),
	LastUpdatedDateTime datetime);

	 
	 
-- End Display Incoming Flight --