//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.06 at 07:22:06 PM SGT 
//


package com.ngen.cosys.altea.fm.amadeus.xml.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * To specify the details of an All Packed In One load for transport on an aircraft.
 * 
 * <p>Java class for AllPackedInOneLoadDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="AllPackedInOneLoadDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="airwayBillNbr" type="{http://xml.amadeus.com/FECFUQ_17_1_1A}AlphaNumericString_Length1To12" minOccurs="0"/>
 *         &lt;element name="description" type="{http://xml.amadeus.com/FECFUQ_17_1_1A}AlphaNumericString_Length1To256" minOccurs="0"/>
 *         &lt;element name="radioactiveCategory" type="{http://xml.amadeus.com/FECFUQ_17_1_1A}AlphaNumericString_Length1To3" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "AllPackedInOneLoadDetailsType", propOrder = {
    "airwayBillNbr",
    "description",
    "radioactiveCategory"
})
public class AllPackedInOneLoadDetailsType {

    protected String airwayBillNbr;
    protected String description;
    protected String radioactiveCategory;

    /**
     * Gets the value of the airwayBillNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirwayBillNbr() {
        return airwayBillNbr;
    }

    /**
     * Sets the value of the airwayBillNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirwayBillNbr(String value) {
        this.airwayBillNbr = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the radioactiveCategory property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRadioactiveCategory() {
        return radioactiveCategory;
    }

    /**
     * Sets the value of the radioactiveCategory property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRadioactiveCategory(String value) {
        this.radioactiveCategory = value;
    }

}
