//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.06 at 07:22:06 PM SGT 
//


package com.ngen.cosys.altea.fm.amadeus.xml.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * To specify outbound and inbound flight information.
 * 
 * <p>Java class for FlightDetailsQueryType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlightDetailsQueryType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="carrierDetails" type="{http://xml.amadeus.com/FECFUQ_17_1_1A}OutboundCarrierDetailsTypeI"/>
 *         &lt;element name="flightDetails" type="{http://xml.amadeus.com/FECFUQ_17_1_1A}OutboundFlightNumberDetailstypeI" minOccurs="0"/>
 *         &lt;element name="offPoint" type="{http://xml.amadeus.com/FECFUQ_17_1_1A}AlphaString_Length1To5" minOccurs="0"/>
 *         &lt;element name="inboundCarrierDetails" type="{http://xml.amadeus.com/FECFUQ_17_1_1A}InboundCarrierDetailsTypeI" minOccurs="0"/>
 *         &lt;element name="inboundFlightDetails" type="{http://xml.amadeus.com/FECFUQ_17_1_1A}InboundFlightNumberDetailsTypeI" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightDetailsQueryType", propOrder = {
    "carrierDetails",
    "flightDetails",
    "offPoint",
    "inboundCarrierDetails",
    "inboundFlightDetails"
})
public class FlightDetailsQueryType {

    @XmlElement(required = true)
    protected OutboundCarrierDetailsTypeI carrierDetails;
    protected OutboundFlightNumberDetailstypeI flightDetails;
    protected String offPoint;
    protected InboundCarrierDetailsTypeI inboundCarrierDetails;
    protected InboundFlightNumberDetailsTypeI inboundFlightDetails;

    /**
     * Gets the value of the carrierDetails property.
     * 
     * @return
     *     possible object is
     *     {@link OutboundCarrierDetailsTypeI }
     *     
     */
    public OutboundCarrierDetailsTypeI getCarrierDetails() {
        return carrierDetails;
    }

    /**
     * Sets the value of the carrierDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutboundCarrierDetailsTypeI }
     *     
     */
    public void setCarrierDetails(OutboundCarrierDetailsTypeI value) {
        this.carrierDetails = value;
    }

    /**
     * Gets the value of the flightDetails property.
     * 
     * @return
     *     possible object is
     *     {@link OutboundFlightNumberDetailstypeI }
     *     
     */
    public OutboundFlightNumberDetailstypeI getFlightDetails() {
        return flightDetails;
    }

    /**
     * Sets the value of the flightDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link OutboundFlightNumberDetailstypeI }
     *     
     */
    public void setFlightDetails(OutboundFlightNumberDetailstypeI value) {
        this.flightDetails = value;
    }

    /**
     * Gets the value of the offPoint property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOffPoint() {
        return offPoint;
    }

    /**
     * Sets the value of the offPoint property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOffPoint(String value) {
        this.offPoint = value;
    }

    /**
     * Gets the value of the inboundCarrierDetails property.
     * 
     * @return
     *     possible object is
     *     {@link InboundCarrierDetailsTypeI }
     *     
     */
    public InboundCarrierDetailsTypeI getInboundCarrierDetails() {
        return inboundCarrierDetails;
    }

    /**
     * Sets the value of the inboundCarrierDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link InboundCarrierDetailsTypeI }
     *     
     */
    public void setInboundCarrierDetails(InboundCarrierDetailsTypeI value) {
        this.inboundCarrierDetails = value;
    }

    /**
     * Gets the value of the inboundFlightDetails property.
     * 
     * @return
     *     possible object is
     *     {@link InboundFlightNumberDetailsTypeI }
     *     
     */
    public InboundFlightNumberDetailsTypeI getInboundFlightDetails() {
        return inboundFlightDetails;
    }

    /**
     * Sets the value of the inboundFlightDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link InboundFlightNumberDetailsTypeI }
     *     
     */
    public void setInboundFlightDetails(InboundFlightNumberDetailsTypeI value) {
        this.inboundFlightDetails = value;
    }

}
