//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.06 at 07:22:06 PM SGT 
//


package com.ngen.cosys.altea.fm.amadeus.xml.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * To describe an item in either an industry or free format.
 * 
 * <p>Java class for ItemDescriptionTypeI complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ItemDescriptionTypeI">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="type" type="{http://xml.amadeus.com/FECFUQ_17_1_1A}AlphaNumericString_Length1To3"/>
 *         &lt;element name="descriptionDetails" type="{http://xml.amadeus.com/FECFUQ_17_1_1A}ItemDescriptionDetailsTypeI"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ItemDescriptionTypeI", propOrder = {
    "type",
    "descriptionDetails"
})
public class ItemDescriptionTypeI {

    @XmlElement(required = true)
    protected String type;
    @XmlElement(required = true)
    protected ItemDescriptionDetailsTypeI descriptionDetails;

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the descriptionDetails property.
     * 
     * @return
     *     possible object is
     *     {@link ItemDescriptionDetailsTypeI }
     *     
     */
    public ItemDescriptionDetailsTypeI getDescriptionDetails() {
        return descriptionDetails;
    }

    /**
     * Sets the value of the descriptionDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link ItemDescriptionDetailsTypeI }
     *     
     */
    public void setDescriptionDetails(ItemDescriptionDetailsTypeI value) {
        this.descriptionDetails = value;
    }

}
