//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.06 at 07:22:06 PM SGT 
//


package com.ngen.cosys.altea.fm.amadeus.xml.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * To specify the details concerning the load to be transported.
 * 
 * <p>Java class for LoadDetailsInformationType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="LoadDetailsInformationType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="loadDetails" type="{http://xml.amadeus.com/FECFUQ_17_1_1A}LoadDetailsType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "LoadDetailsInformationType", propOrder = {
    "loadDetails"
})
public class LoadDetailsInformationType {

    @XmlElement(required = true)
    protected LoadDetailsType loadDetails;

    /**
     * Gets the value of the loadDetails property.
     * 
     * @return
     *     possible object is
     *     {@link LoadDetailsType }
     *     
     */
    public LoadDetailsType getLoadDetails() {
        return loadDetails;
    }

    /**
     * Sets the value of the loadDetails property.
     * 
     * @param value
     *     allowed object is
     *     {@link LoadDetailsType }
     *     
     */
    public void setLoadDetails(LoadDetailsType value) {
        this.loadDetails = value;
    }

}
