//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.06 at 07:22:06 PM SGT 
//


package com.ngen.cosys.altea.fm.amadeus.xml.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * To specify Physical Measurements.
 * 
 * <p>Java class for MeasurementsType_92900S complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="MeasurementsType_92900S">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="measurementQualifier" type="{http://xml.amadeus.com/FECFUQ_17_1_1A}AMA_EDICodesetType_Length1to3"/>
 *         &lt;element name="valueRange" type="{http://xml.amadeus.com/FECFUQ_17_1_1A}ValueRangeTypeI" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "MeasurementsType_92900S", propOrder = {
    "measurementQualifier",
    "valueRange"
})
public class MeasurementsType92900S {

    @XmlElement(required = true)
    protected String measurementQualifier;
    protected ValueRangeTypeI valueRange;

    /**
     * Gets the value of the measurementQualifier property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMeasurementQualifier() {
        return measurementQualifier;
    }

    /**
     * Sets the value of the measurementQualifier property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMeasurementQualifier(String value) {
        this.measurementQualifier = value;
    }

    /**
     * Gets the value of the valueRange property.
     * 
     * @return
     *     possible object is
     *     {@link ValueRangeTypeI }
     *     
     */
    public ValueRangeTypeI getValueRange() {
        return valueRange;
    }

    /**
     * Sets the value of the valueRange property.
     * 
     * @param value
     *     allowed object is
     *     {@link ValueRangeTypeI }
     *     
     */
    public void setValueRange(ValueRangeTypeI value) {
        this.valueRange = value;
    }

}
