//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.06 at 07:22:06 PM SGT 
//


package com.ngen.cosys.altea.fm.amadeus.xml.request;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ngen.cosys.altea.fm.amadeus.xml.request package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ngen.cosys.altea.fm.amadeus.xml.request
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DCSFMUpdateCargoFigures }
     * 
     */
    public DCSFMUpdateCargoFigures createDCSFMUpdateCargoFigures() {
        return new DCSFMUpdateCargoFigures();
    }

    /**
     * Create an instance of {@link DCSFMUpdateCargoFigures.LoadInfo }
     * 
     */
    public DCSFMUpdateCargoFigures.LoadInfo createDCSFMUpdateCargoFiguresLoadInfo() {
        return new DCSFMUpdateCargoFigures.LoadInfo();
    }

    /**
     * Create an instance of {@link DCSFMUpdateCargoFigures.LoadInfo.DeadloadForLoad }
     * 
     */
    public DCSFMUpdateCargoFigures.LoadInfo.DeadloadForLoad createDCSFMUpdateCargoFiguresLoadInfoDeadloadForLoad() {
        return new DCSFMUpdateCargoFigures.LoadInfo.DeadloadForLoad();
    }

    /**
     * Create an instance of {@link DCSFMUpdateCargoFigures.LoadInfo.DeadloadForLoad.OverpackForDeadload }
     * 
     */
    public DCSFMUpdateCargoFigures.LoadInfo.DeadloadForLoad.OverpackForDeadload createDCSFMUpdateCargoFiguresLoadInfoDeadloadForLoadOverpackForDeadload() {
        return new DCSFMUpdateCargoFigures.LoadInfo.DeadloadForLoad.OverpackForDeadload();
    }

    /**
     * Create an instance of {@link DCSFMUpdateCargoFigures.LoadInfo.DeadloadForLoad.OverpackForDeadload.AllPackedInOneForOVP }
     * 
     */
    public DCSFMUpdateCargoFigures.LoadInfo.DeadloadForLoad.OverpackForDeadload.AllPackedInOneForOVP createDCSFMUpdateCargoFiguresLoadInfoDeadloadForLoadOverpackForDeadloadAllPackedInOneForOVP() {
        return new DCSFMUpdateCargoFigures.LoadInfo.DeadloadForLoad.OverpackForDeadload.AllPackedInOneForOVP();
    }

    /**
     * Create an instance of {@link DCSFMUpdateCargoFigures.LoadInfo.DeadloadForLoad.AllPackedInOneForDeadload }
     * 
     */
    public DCSFMUpdateCargoFigures.LoadInfo.DeadloadForLoad.AllPackedInOneForDeadload createDCSFMUpdateCargoFiguresLoadInfoDeadloadForLoadAllPackedInOneForDeadload() {
        return new DCSFMUpdateCargoFigures.LoadInfo.DeadloadForLoad.AllPackedInOneForDeadload();
    }

    /**
     * Create an instance of {@link TransportIdentifierType }
     * 
     */
    public TransportIdentifierType createTransportIdentifierType() {
        return new TransportIdentifierType();
    }

    /**
     * Create an instance of {@link StructuredDateTimeInformationType }
     * 
     */
    public StructuredDateTimeInformationType createStructuredDateTimeInformationType() {
        return new StructuredDateTimeInformationType();
    }

    /**
     * Create an instance of {@link OriginAndDestinationDetailsTypeI67289S }
     * 
     */
    public OriginAndDestinationDetailsTypeI67289S createOriginAndDestinationDetailsTypeI67289S() {
        return new OriginAndDestinationDetailsTypeI67289S();
    }

    /**
     * Create an instance of {@link ReferenceInformationTypeI84021S }
     * 
     */
    public ReferenceInformationTypeI84021S createReferenceInformationTypeI84021S() {
        return new ReferenceInformationTypeI84021S();
    }

    /**
     * Create an instance of {@link EquipmentInformationType }
     * 
     */
    public EquipmentInformationType createEquipmentInformationType() {
        return new EquipmentInformationType();
    }

    /**
     * Create an instance of {@link TravellerInformationTypeI }
     * 
     */
    public TravellerInformationTypeI createTravellerInformationTypeI() {
        return new TravellerInformationTypeI();
    }

    /**
     * Create an instance of {@link DummySegmentTypeI }
     * 
     */
    public DummySegmentTypeI createDummySegmentTypeI() {
        return new DummySegmentTypeI();
    }

    /**
     * Create an instance of {@link ReferenceInformationTypeI84045S }
     * 
     */
    public ReferenceInformationTypeI84045S createReferenceInformationTypeI84045S() {
        return new ReferenceInformationTypeI84045S();
    }

    /**
     * Create an instance of {@link PhoneAndEmailAddressType }
     * 
     */
    public PhoneAndEmailAddressType createPhoneAndEmailAddressType() {
        return new PhoneAndEmailAddressType();
    }

    /**
     * Create an instance of {@link InteractiveFreeTextTypeI84224S }
     * 
     */
    public InteractiveFreeTextTypeI84224S createInteractiveFreeTextTypeI84224S() {
        return new InteractiveFreeTextTypeI84224S();
    }

    /**
     * Create an instance of {@link StatusTypeI84225S }
     * 
     */
    public StatusTypeI84225S createStatusTypeI84225S() {
        return new StatusTypeI84225S();
    }

    /**
     * Create an instance of {@link StructuredDateTimeInformationType84018S }
     * 
     */
    public StructuredDateTimeInformationType84018S createStructuredDateTimeInformationType84018S() {
        return new StructuredDateTimeInformationType84018S();
    }

    /**
     * Create an instance of {@link ReferenceInformationTypeI92892S }
     * 
     */
    public ReferenceInformationTypeI92892S createReferenceInformationTypeI92892S() {
        return new ReferenceInformationTypeI92892S();
    }

    /**
     * Create an instance of {@link StatusTypeI83998S }
     * 
     */
    public StatusTypeI83998S createStatusTypeI83998S() {
        return new StatusTypeI83998S();
    }

    /**
     * Create an instance of {@link NumberOfUnitsType83983S }
     * 
     */
    public NumberOfUnitsType83983S createNumberOfUnitsType83983S() {
        return new NumberOfUnitsType83983S();
    }

    /**
     * Create an instance of {@link ReferencingDetailsTypeI }
     * 
     */
    public ReferencingDetailsTypeI createReferencingDetailsTypeI() {
        return new ReferencingDetailsTypeI();
    }

    /**
     * Create an instance of {@link InboundFlightNumberDetailsTypeI }
     * 
     */
    public InboundFlightNumberDetailsTypeI createInboundFlightNumberDetailsTypeI() {
        return new InboundFlightNumberDetailsTypeI();
    }

    /**
     * Create an instance of {@link ReferenceInformationTypeI83948S }
     * 
     */
    public ReferenceInformationTypeI83948S createReferenceInformationTypeI83948S() {
        return new ReferenceInformationTypeI83948S();
    }

    /**
     * Create an instance of {@link ReferenceInfoType }
     * 
     */
    public ReferenceInfoType createReferenceInfoType() {
        return new ReferenceInfoType();
    }

    /**
     * Create an instance of {@link OriginAndDestinationDetailsTypeI }
     * 
     */
    public OriginAndDestinationDetailsTypeI createOriginAndDestinationDetailsTypeI() {
        return new OriginAndDestinationDetailsTypeI();
    }

    /**
     * Create an instance of {@link LoadDetailsInformationType92764S }
     * 
     */
    public LoadDetailsInformationType92764S createLoadDetailsInformationType92764S() {
        return new LoadDetailsInformationType92764S();
    }

    /**
     * Create an instance of {@link InteractiveFreeTextTypeI }
     * 
     */
    public InteractiveFreeTextTypeI createInteractiveFreeTextTypeI() {
        return new InteractiveFreeTextTypeI();
    }

    /**
     * Create an instance of {@link CompanyIdentificationTypeI }
     * 
     */
    public CompanyIdentificationTypeI createCompanyIdentificationTypeI() {
        return new CompanyIdentificationTypeI();
    }

    /**
     * Create an instance of {@link LoadDetailsType }
     * 
     */
    public LoadDetailsType createLoadDetailsType() {
        return new LoadDetailsType();
    }

    /**
     * Create an instance of {@link ReferencingDetailsType }
     * 
     */
    public ReferencingDetailsType createReferencingDetailsType() {
        return new ReferencingDetailsType();
    }

    /**
     * Create an instance of {@link ValueRangeTypeI }
     * 
     */
    public ValueRangeTypeI createValueRangeTypeI() {
        return new ValueRangeTypeI();
    }

    /**
     * Create an instance of {@link ItemDescriptionTypeI92894S }
     * 
     */
    public ItemDescriptionTypeI92894S createItemDescriptionTypeI92894S() {
        return new ItemDescriptionTypeI92894S();
    }

    /**
     * Create an instance of {@link ReferencingDetailsTypeI139763C }
     * 
     */
    public ReferencingDetailsTypeI139763C createReferencingDetailsTypeI139763C() {
        return new ReferencingDetailsTypeI139763C();
    }

    /**
     * Create an instance of {@link StatusDetailsTypeI }
     * 
     */
    public StatusDetailsTypeI createStatusDetailsTypeI() {
        return new StatusDetailsTypeI();
    }

    /**
     * Create an instance of {@link ItemDescriptionDetailsTypeI139765C }
     * 
     */
    public ItemDescriptionDetailsTypeI139765C createItemDescriptionDetailsTypeI139765C() {
        return new ItemDescriptionDetailsTypeI139765C();
    }

    /**
     * Create an instance of {@link ItemDescriptionTypeI92732S }
     * 
     */
    public ItemDescriptionTypeI92732S createItemDescriptionTypeI92732S() {
        return new ItemDescriptionTypeI92732S();
    }

    /**
     * Create an instance of {@link InboundCarrierDetailsTypeI }
     * 
     */
    public InboundCarrierDetailsTypeI createInboundCarrierDetailsTypeI() {
        return new InboundCarrierDetailsTypeI();
    }

    /**
     * Create an instance of {@link OutboundFlightNumberDetailstypeI }
     * 
     */
    public OutboundFlightNumberDetailstypeI createOutboundFlightNumberDetailstypeI() {
        return new OutboundFlightNumberDetailstypeI();
    }

    /**
     * Create an instance of {@link FreeTextQualificationTypeI }
     * 
     */
    public FreeTextQualificationTypeI createFreeTextQualificationTypeI() {
        return new FreeTextQualificationTypeI();
    }

    /**
     * Create an instance of {@link TravellerDetailsTypeI }
     * 
     */
    public TravellerDetailsTypeI createTravellerDetailsTypeI() {
        return new TravellerDetailsTypeI();
    }

    /**
     * Create an instance of {@link NumberOfUnitDetailsTypeI }
     * 
     */
    public NumberOfUnitDetailsTypeI createNumberOfUnitDetailsTypeI() {
        return new NumberOfUnitDetailsTypeI();
    }

    /**
     * Create an instance of {@link TravellerSurnameInformationTypeI }
     * 
     */
    public TravellerSurnameInformationTypeI createTravellerSurnameInformationTypeI() {
        return new TravellerSurnameInformationTypeI();
    }

    /**
     * Create an instance of {@link HazardIdentificationTypeI }
     * 
     */
    public HazardIdentificationTypeI createHazardIdentificationTypeI() {
        return new HazardIdentificationTypeI();
    }

    /**
     * Create an instance of {@link QuantityDetailsType }
     * 
     */
    public QuantityDetailsType createQuantityDetailsType() {
        return new QuantityDetailsType();
    }

    /**
     * Create an instance of {@link StatusDetailsTypeI128105C }
     * 
     */
    public StatusDetailsTypeI128105C createStatusDetailsTypeI128105C() {
        return new StatusDetailsTypeI128105C();
    }

    /**
     * Create an instance of {@link CargoDetailsType }
     * 
     */
    public CargoDetailsType createCargoDetailsType() {
        return new CargoDetailsType();
    }

    /**
     * Create an instance of {@link QuantityDetailsTypeI }
     * 
     */
    public QuantityDetailsTypeI createQuantityDetailsTypeI() {
        return new QuantityDetailsTypeI();
    }

    /**
     * Create an instance of {@link OverpackLoadDetailsType }
     * 
     */
    public OverpackLoadDetailsType createOverpackLoadDetailsType() {
        return new OverpackLoadDetailsType();
    }

    /**
     * Create an instance of {@link FlightDetailsQueryType }
     * 
     */
    public FlightDetailsQueryType createFlightDetailsQueryType() {
        return new FlightDetailsQueryType();
    }

    /**
     * Create an instance of {@link InteractiveFreeTextType }
     * 
     */
    public InteractiveFreeTextType createInteractiveFreeTextType() {
        return new InteractiveFreeTextType();
    }

    /**
     * Create an instance of {@link ReferenceInfoType193774S }
     * 
     */
    public ReferenceInfoType193774S createReferenceInfoType193774S() {
        return new ReferenceInfoType193774S();
    }

    /**
     * Create an instance of {@link MeasurementsType92900S }
     * 
     */
    public MeasurementsType92900S createMeasurementsType92900S() {
        return new MeasurementsType92900S();
    }

    /**
     * Create an instance of {@link NumberOfUnitDetailsType }
     * 
     */
    public NumberOfUnitDetailsType createNumberOfUnitDetailsType() {
        return new NumberOfUnitDetailsType();
    }

    /**
     * Create an instance of {@link ReferenceInformationTypeI }
     * 
     */
    public ReferenceInformationTypeI createReferenceInformationTypeI() {
        return new ReferenceInformationTypeI();
    }

    /**
     * Create an instance of {@link MeasurementsType }
     * 
     */
    public MeasurementsType createMeasurementsType() {
        return new MeasurementsType();
    }

    /**
     * Create an instance of {@link SpecialLoadDetailsType }
     * 
     */
    public SpecialLoadDetailsType createSpecialLoadDetailsType() {
        return new SpecialLoadDetailsType();
    }

    /**
     * Create an instance of {@link QuantityType92784S }
     * 
     */
    public QuantityType92784S createQuantityType92784S() {
        return new QuantityType92784S();
    }

    /**
     * Create an instance of {@link ItemDescriptionTypeI }
     * 
     */
    public ItemDescriptionTypeI createItemDescriptionTypeI() {
        return new ItemDescriptionTypeI();
    }

    /**
     * Create an instance of {@link ReferenceInfoType175451S }
     * 
     */
    public ReferenceInfoType175451S createReferenceInfoType175451S() {
        return new ReferenceInfoType175451S();
    }

    /**
     * Create an instance of {@link NumberOfUnitsType }
     * 
     */
    public NumberOfUnitsType createNumberOfUnitsType() {
        return new NumberOfUnitsType();
    }

    /**
     * Create an instance of {@link QuantityType }
     * 
     */
    public QuantityType createQuantityType() {
        return new QuantityType();
    }

    /**
     * Create an instance of {@link StructuredDateTimeType }
     * 
     */
    public StructuredDateTimeType createStructuredDateTimeType() {
        return new StructuredDateTimeType();
    }

    /**
     * Create an instance of {@link ProductIdentificationDetailsTypeI }
     * 
     */
    public ProductIdentificationDetailsTypeI createProductIdentificationDetailsTypeI() {
        return new ProductIdentificationDetailsTypeI();
    }

    /**
     * Create an instance of {@link QuantityTypeI }
     * 
     */
    public QuantityTypeI createQuantityTypeI() {
        return new QuantityTypeI();
    }

    /**
     * Create an instance of {@link StatusDetailsTypeI171610C }
     * 
     */
    public StatusDetailsTypeI171610C createStatusDetailsTypeI171610C() {
        return new StatusDetailsTypeI171610C();
    }

    /**
     * Create an instance of {@link ItemDescriptionDetailsTypeI }
     * 
     */
    public ItemDescriptionDetailsTypeI createItemDescriptionDetailsTypeI() {
        return new ItemDescriptionDetailsTypeI();
    }

    /**
     * Create an instance of {@link AllPackedInOneLoadDetailsType }
     * 
     */
    public AllPackedInOneLoadDetailsType createAllPackedInOneLoadDetailsType() {
        return new AllPackedInOneLoadDetailsType();
    }

    /**
     * Create an instance of {@link StructuredTelephoneNumberType }
     * 
     */
    public StructuredTelephoneNumberType createStructuredTelephoneNumberType() {
        return new StructuredTelephoneNumberType();
    }

    /**
     * Create an instance of {@link ReferencingDetailsTypeI128135C }
     * 
     */
    public ReferencingDetailsTypeI128135C createReferencingDetailsTypeI128135C() {
        return new ReferencingDetailsTypeI128135C();
    }

    /**
     * Create an instance of {@link EquipmentIdentificationType }
     * 
     */
    public EquipmentIdentificationType createEquipmentIdentificationType() {
        return new EquipmentIdentificationType();
    }

    /**
     * Create an instance of {@link StatusDetailsType }
     * 
     */
    public StatusDetailsType createStatusDetailsType() {
        return new StatusDetailsType();
    }

    /**
     * Create an instance of {@link ReferencingDetailsType247148C }
     * 
     */
    public ReferencingDetailsType247148C createReferencingDetailsType247148C() {
        return new ReferencingDetailsType247148C();
    }

    /**
     * Create an instance of {@link StatusTypeI }
     * 
     */
    public StatusTypeI createStatusTypeI() {
        return new StatusTypeI();
    }

    /**
     * Create an instance of {@link OutboundCarrierDetailsTypeI }
     * 
     */
    public OutboundCarrierDetailsTypeI createOutboundCarrierDetailsTypeI() {
        return new OutboundCarrierDetailsTypeI();
    }

    /**
     * Create an instance of {@link StructuredDateTimeType129165C }
     * 
     */
    public StructuredDateTimeType129165C createStructuredDateTimeType129165C() {
        return new StructuredDateTimeType129165C();
    }

    /**
     * Create an instance of {@link StatusType }
     * 
     */
    public StatusType createStatusType() {
        return new StatusType();
    }

    /**
     * Create an instance of {@link LoadDetailsInformationType }
     * 
     */
    public LoadDetailsInformationType createLoadDetailsInformationType() {
        return new LoadDetailsInformationType();
    }

    /**
     * Create an instance of {@link ValueRangeType }
     * 
     */
    public ValueRangeType createValueRangeType() {
        return new ValueRangeType();
    }

    /**
     * Create an instance of {@link ItemDescriptionDetailsTypeI139541C }
     * 
     */
    public ItemDescriptionDetailsTypeI139541C createItemDescriptionDetailsTypeI139541C() {
        return new ItemDescriptionDetailsTypeI139541C();
    }

    /**
     * Create an instance of {@link HazardCodeType }
     * 
     */
    public HazardCodeType createHazardCodeType() {
        return new HazardCodeType();
    }

    /**
     * Create an instance of {@link QuantityType83982S }
     * 
     */
    public QuantityType83982S createQuantityType83982S() {
        return new QuantityType83982S();
    }

    /**
     * Create an instance of {@link DCSFMUpdateCargoFigures.LoadInfo.NetWeightCentre }
     * 
     */
    public DCSFMUpdateCargoFigures.LoadInfo.NetWeightCentre createDCSFMUpdateCargoFiguresLoadInfoNetWeightCentre() {
        return new DCSFMUpdateCargoFigures.LoadInfo.NetWeightCentre();
    }

    /**
     * Create an instance of {@link DCSFMUpdateCargoFigures.LoadInfo.DeadloadForLoad.DgslForDeadload }
     * 
     */
    public DCSFMUpdateCargoFigures.LoadInfo.DeadloadForLoad.DgslForDeadload createDCSFMUpdateCargoFiguresLoadInfoDeadloadForLoadDgslForDeadload() {
        return new DCSFMUpdateCargoFigures.LoadInfo.DeadloadForLoad.DgslForDeadload();
    }

    /**
     * Create an instance of {@link DCSFMUpdateCargoFigures.LoadInfo.DeadloadForLoad.OverpackForDeadload.DgslForOVP }
     * 
     */
    public DCSFMUpdateCargoFigures.LoadInfo.DeadloadForLoad.OverpackForDeadload.DgslForOVP createDCSFMUpdateCargoFiguresLoadInfoDeadloadForLoadOverpackForDeadloadDgslForOVP() {
        return new DCSFMUpdateCargoFigures.LoadInfo.DeadloadForLoad.OverpackForDeadload.DgslForOVP();
    }

    /**
     * Create an instance of {@link DCSFMUpdateCargoFigures.LoadInfo.DeadloadForLoad.OverpackForDeadload.AllPackedInOneForOVP.DgslForAPIO }
     * 
     */
    public DCSFMUpdateCargoFigures.LoadInfo.DeadloadForLoad.OverpackForDeadload.AllPackedInOneForOVP.DgslForAPIO createDCSFMUpdateCargoFiguresLoadInfoDeadloadForLoadOverpackForDeadloadAllPackedInOneForOVPDgslForAPIO() {
        return new DCSFMUpdateCargoFigures.LoadInfo.DeadloadForLoad.OverpackForDeadload.AllPackedInOneForOVP.DgslForAPIO();
    }

    /**
     * Create an instance of {@link DCSFMUpdateCargoFigures.LoadInfo.DeadloadForLoad.AllPackedInOneForDeadload.DgslForAPIO }
     * 
     */
    public DCSFMUpdateCargoFigures.LoadInfo.DeadloadForLoad.AllPackedInOneForDeadload.DgslForAPIO createDCSFMUpdateCargoFiguresLoadInfoDeadloadForLoadAllPackedInOneForDeadloadDgslForAPIO() {
        return new DCSFMUpdateCargoFigures.LoadInfo.DeadloadForLoad.AllPackedInOneForDeadload.DgslForAPIO();
    }

}
