//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.06 at 07:22:06 PM SGT 
//


package com.ngen.cosys.altea.fm.amadeus.xml.request;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * To identify the details concerning a special load to be transported.
 * 
 * <p>Java class for SpecialLoadDetailsType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="SpecialLoadDetailsType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="emergencyRespCode" type="{http://xml.amadeus.com/FECFUQ_17_1_1A}AlphaNumericString_Length1To3" minOccurs="0"/>
 *         &lt;element name="airwayBillNbr" type="{http://xml.amadeus.com/FECFUQ_17_1_1A}AlphaNumericString_Length1To12" minOccurs="0"/>
 *         &lt;element name="uNOrIDNbr" type="{http://xml.amadeus.com/FECFUQ_17_1_1A}AlphaNumericString_Length4To4" minOccurs="0"/>
 *         &lt;element name="description" type="{http://xml.amadeus.com/FECFUQ_17_1_1A}AlphaNumericString_Length1To256" minOccurs="0"/>
 *         &lt;element name="sldgPackingGroup" type="{http://xml.amadeus.com/FECFUQ_17_1_1A}AlphaNumericString_Length1To3" minOccurs="0"/>
 *         &lt;element name="hazardID" type="{http://xml.amadeus.com/FECFUQ_17_1_1A}HazardIdentificationTypeI" minOccurs="0"/>
 *         &lt;element name="hazardReference" type="{http://xml.amadeus.com/FECFUQ_17_1_1A}HazardCodeType" minOccurs="0"/>
 *         &lt;element name="technicalDescription" type="{http://xml.amadeus.com/FECFUQ_17_1_1A}AlphaNumericString_Length1To256" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "SpecialLoadDetailsType", propOrder = {
    "emergencyRespCode",
    "airwayBillNbr",
    "unOrIDNbr",
    "description",
    "sldgPackingGroup",
    "hazardID",
    "hazardReference",
    "technicalDescription"
})
public class SpecialLoadDetailsType {

    protected String emergencyRespCode;
    protected String airwayBillNbr;
    @XmlElement(name = "uNOrIDNbr")
    protected String unOrIDNbr;
    protected String description;
    protected String sldgPackingGroup;
    protected HazardIdentificationTypeI hazardID;
    protected HazardCodeType hazardReference;
    protected String technicalDescription;

    /**
     * Gets the value of the emergencyRespCode property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmergencyRespCode() {
        return emergencyRespCode;
    }

    /**
     * Sets the value of the emergencyRespCode property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmergencyRespCode(String value) {
        this.emergencyRespCode = value;
    }

    /**
     * Gets the value of the airwayBillNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAirwayBillNbr() {
        return airwayBillNbr;
    }

    /**
     * Sets the value of the airwayBillNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAirwayBillNbr(String value) {
        this.airwayBillNbr = value;
    }

    /**
     * Gets the value of the unOrIDNbr property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getUNOrIDNbr() {
        return unOrIDNbr;
    }

    /**
     * Sets the value of the unOrIDNbr property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setUNOrIDNbr(String value) {
        this.unOrIDNbr = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the sldgPackingGroup property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSldgPackingGroup() {
        return sldgPackingGroup;
    }

    /**
     * Sets the value of the sldgPackingGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSldgPackingGroup(String value) {
        this.sldgPackingGroup = value;
    }

    /**
     * Gets the value of the hazardID property.
     * 
     * @return
     *     possible object is
     *     {@link HazardIdentificationTypeI }
     *     
     */
    public HazardIdentificationTypeI getHazardID() {
        return hazardID;
    }

    /**
     * Sets the value of the hazardID property.
     * 
     * @param value
     *     allowed object is
     *     {@link HazardIdentificationTypeI }
     *     
     */
    public void setHazardID(HazardIdentificationTypeI value) {
        this.hazardID = value;
    }

    /**
     * Gets the value of the hazardReference property.
     * 
     * @return
     *     possible object is
     *     {@link HazardCodeType }
     *     
     */
    public HazardCodeType getHazardReference() {
        return hazardReference;
    }

    /**
     * Sets the value of the hazardReference property.
     * 
     * @param value
     *     allowed object is
     *     {@link HazardCodeType }
     *     
     */
    public void setHazardReference(HazardCodeType value) {
        this.hazardReference = value;
    }

    /**
     * Gets the value of the technicalDescription property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTechnicalDescription() {
        return technicalDescription;
    }

    /**
     * Sets the value of the technicalDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTechnicalDescription(String value) {
        this.technicalDescription = value;
    }

}
