//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.06 at 07:23:15 PM SGT 
//


package com.ngen.cosys.altea.fm.amadeus.xml.response;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="flightId" type="{http://xml.amadeus.com/FECFUR_17_1_1A}FlightDetailsResponseType" minOccurs="0"/>
 *         &lt;element name="error" type="{http://xml.amadeus.com/FECFUR_17_1_1A}ErrorGroupType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "flightId",
    "error"
})
@XmlRootElement(name = "DCSFM_UpdateCargoFiguresReply")
public class DCSFMUpdateCargoFiguresReply {

    protected FlightDetailsResponseType flightId;
    protected ErrorGroupType error;

    /**
     * Gets the value of the flightId property.
     * 
     * @return
     *     possible object is
     *     {@link FlightDetailsResponseType }
     *     
     */
    public FlightDetailsResponseType getFlightId() {
        return flightId;
    }

    /**
     * Sets the value of the flightId property.
     * 
     * @param value
     *     allowed object is
     *     {@link FlightDetailsResponseType }
     *     
     */
    public void setFlightId(FlightDetailsResponseType value) {
        this.flightId = value;
    }

    /**
     * Gets the value of the error property.
     * 
     * @return
     *     possible object is
     *     {@link ErrorGroupType }
     *     
     */
    public ErrorGroupType getError() {
        return error;
    }

    /**
     * Sets the value of the error property.
     * 
     * @param value
     *     allowed object is
     *     {@link ErrorGroupType }
     *     
     */
    public void setError(ErrorGroupType value) {
        this.error = value;
    }

}
