//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.06 at 07:23:15 PM SGT 
//


package com.ngen.cosys.altea.fm.amadeus.xml.response;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.ngen.cosys.altea.fm.amadeus.xml.response package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.ngen.cosys.altea.fm.amadeus.xml.response
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DCSFMUpdateCargoFiguresReply }
     * 
     */
    public DCSFMUpdateCargoFiguresReply createDCSFMUpdateCargoFiguresReply() {
        return new DCSFMUpdateCargoFiguresReply();
    }

    /**
     * Create an instance of {@link FlightDetailsResponseType }
     * 
     */
    public FlightDetailsResponseType createFlightDetailsResponseType() {
        return new FlightDetailsResponseType();
    }

    /**
     * Create an instance of {@link ErrorGroupType }
     * 
     */
    public ErrorGroupType createErrorGroupType() {
        return new ErrorGroupType();
    }

    /**
     * Create an instance of {@link ApplicationErrorInformationType }
     * 
     */
    public ApplicationErrorInformationType createApplicationErrorInformationType() {
        return new ApplicationErrorInformationType();
    }

    /**
     * Create an instance of {@link FreeTextDetailsType }
     * 
     */
    public FreeTextDetailsType createFreeTextDetailsType() {
        return new FreeTextDetailsType();
    }

    /**
     * Create an instance of {@link ApplicationErrorDetailType }
     * 
     */
    public ApplicationErrorDetailType createApplicationErrorDetailType() {
        return new ApplicationErrorDetailType();
    }

    /**
     * Create an instance of {@link OutboundFlightNumberDetailstypeI }
     * 
     */
    public OutboundFlightNumberDetailstypeI createOutboundFlightNumberDetailstypeI() {
        return new OutboundFlightNumberDetailstypeI();
    }

    /**
     * Create an instance of {@link OutboundCarrierDetailsTypeI }
     * 
     */
    public OutboundCarrierDetailsTypeI createOutboundCarrierDetailsTypeI() {
        return new OutboundCarrierDetailsTypeI();
    }

    /**
     * Create an instance of {@link FreeTextInformationType }
     * 
     */
    public FreeTextInformationType createFreeTextInformationType() {
        return new FreeTextInformationType();
    }

}
