//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2019.07.06 at 07:23:15 PM SGT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://xml.amadeus.com/FECFUR_17_1_1A", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.ngen.cosys.altea.fm.amadeus.xml.response;
