package com.ngen.cosys.icms.model.bookingicms;

import org.springframework.stereotype.Component;

import lombok.Getter;
import lombok.Setter;


@Component
@Getter
@Setter
public class BookingPublishOutboundSampleBo {
private String sampleRequest="<soapenv:Envelope xmlns:soapenv=\"http://schemas.xmlsoap.org/soap/envelope/\" xmlns:_01=\"http://www.ibsplc.com/icargo/services/CapacityBookingService/2013/06/04_01\" xmlns:_011=\"http://www.ibsplc.com/icargo/services/types/CapacityBookingService/2013/06/04_01\">\r\n"
		+ "<soapenv:Header>\r\n"
		+ "	<wsse:Security xmlns:wsse=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\">\r\n"
		+ "		<wsse:UsernameToken>\r\n"
		+ "			<wsse:Username>SATS</wsse:Username>\r\n"
		+ "			<wsse:Password>Icm$2S@ts</wsse:Password>\r\n"
		+ "		 </wsse:UsernameToken>\r\n"
		+ "	</wsse:Security>\r\n"
		+ "</soapenv:Header>\r\n"
		+ "   <soapenv:Body>\r\n"
		+ "      <_01:SaveBookingDetailsRequest>\r\n"
		+ "         <_011:messageHeader>\r\n"
		+ "            <!--anonymous type - enumeration: [D,A]-->\r\n"
		+ "            <messageType>D</messageType>\r\n"
		+ "            <!--anonymous type-->\r\n"
		+ "            <sourceSystem>COSYS</sourceSystem>\r\n"
		+ "            <!--Optional:-->\r\n"
		+ "            <!--anonymous type-->\r\n"
		+ "            <!--userId>?</userId-->\r\n"
		+ "            <!--Optional:-->\r\n"
		+ "            <!--anonymous type-->\r\n"
		+ "            <!--messageID>?</messageID-->\r\n"
		+ "            <!--Optional:-->\r\n"
		+ "            <!--anonymous type-->\r\n"
		+ "            <correlationID>correlationID005</correlationID>\r\n"
		+ "         </_011:messageHeader>\r\n"
		+ "         <_011:requestData>\r\n"
		+ "            <!--type: t300-->\r\n"
		+ "            <_011:requestID>005</_011:requestID>\r\n"
		+ "            <!--Optional:-->\r\n"
		+ "            <!--type: operationalFlagType - enumeration: [I,U,D]-->\r\n"
		+ "            <_011:operationalFlag>I</_011:operationalFlag>\r\n"
		+ "          <_011:bookingDetails>\r\n"
		+ "               <!--_011:ubrNumber>AUTOUSER1SINCDG124</_011:ubrNumber-->\r\n"
		+ "               <_011:bookingStatus>C</_011:bookingStatus>\r\n"
		+ "               <_011:slacPieces>0</_011:slacPieces>\r\n"
		+ "               <_011:capacityType>F</_011:capacityType>\r\n"
		+ "               <_011:baselineStatus>D</_011:baselineStatus>\r\n"
		+ "               <_011:ccShipmentIndicator>false</_011:ccShipmentIndicator>\r\n"
		+ "               <_011:latestAcceptanceTime>08-Sep-2021 06:00:00</_011:latestAcceptanceTime>\r\n"
		+ "               <_011:latestAcceptanceTimeUTC>07-Sep-2021 22:00:00</_011:latestAcceptanceTimeUTC>\r\n"
		+ "               <_011:reBookingReasonCode>DUM2</_011:reBookingReasonCode>\r\n"
		+ "               <_011:userStation>SIN</_011:userStation>\r\n"
		+ "               <_011:isSplitBooking>false</_011:isSplitBooking>\r\n"
		+ "               <_011:bookingVersion>2</_011:bookingVersion>\r\n"
		+ "               <_011:airFreightCharge>16700.000</_011:airFreightCharge>\r\n"
		+ "               <_011:weightUnit>K</_011:weightUnit>\r\n"
		+ "               <_011:volumeUnit>B</_011:volumeUnit>\r\n"
		+ "               <_011:dimensionUnit>C</_011:dimensionUnit>\r\n"
		+ "               <_011:allInRate>N</_011:allInRate>\r\n"
		+ "               <_011:allInAttribute/>\r\n"
		+ "               <_011:lastUpdateSource>COSYS</_011:lastUpdateSource>\r\n"
		+ "               <_011:isAWBAutoPopulatedFromStock>false</_011:isAWBAutoPopulatedFromStock>\r\n"
		+ "               <_011:bookingDate>07-Sep-2021 06:48:00</_011:bookingDate>\r\n"
		+ "               <_011:bookingDateUTC>07-Sep-2021 06:48:39</_011:bookingDateUTC>\r\n"
		+ "               <_011:createdUser>SATS</_011:createdUser>\r\n"
		+ "               <_011:sccCodes>GEN</_011:sccCodes>\r\n"
		+ "               <_011:autoAllocationEligible>N</_011:autoAllocationEligible>\r\n"
		+ "               <_011:shipmentIdentifierDetails>\r\n"
		+ "                  <_011:shipmentPrefix>618</_011:shipmentPrefix>\r\n"
		+ "                  <_011:masterDocumentNumber>63000663</_011:masterDocumentNumber>\r\n"
		+ "                  <_011:sequenceNumber>1</_011:sequenceNumber>\r\n"
		+ "                  <_011:duplicateNumber>1</_011:duplicateNumber>\r\n"
		+ "                  <_011:ownerCode>SQ</_011:ownerCode>\r\n"
		+ "                  <_011:isNonStandard>false</_011:isNonStandard>\r\n"
		+ "               </_011:shipmentIdentifierDetails>\r\n"
		+ "               <_011:shipmentDetails>\r\n"
		+ "                  <_011:shipmentOrigin>SIN</_011:shipmentOrigin>\r\n"
		+ "                  <_011:shipmentDestination>CDG</_011:shipmentDestination>\r\n"
		+ "                  <_011:shippingDate>08-Sep-2021</_011:shippingDate>\r\n"
		+ "                  <_011:agentCode>AUTOUSER1</_011:agentCode>\r\n"
		+ "                  <_011:agentName>AUTOUSER1NAME</_011:agentName>\r\n"
		+ "                  <_011:agentIataCode>1234765</_011:agentIataCode>\r\n"
		+ "                  <_011:bookingStation>SIN</_011:bookingStation>\r\n"
		+ "                  <_011:customerCode>AUTOUSER1</_011:customerCode>\r\n"
		+ "                  <_011:customerName>AUTOUSER1NAME</_011:customerName>\r\n"
		+ "                  <_011:bookingSource>S</_011:bookingSource>\r\n"
		+ "                  <_011:currency>SGD</_011:currency>\r\n"
		+ "                  <_011:totalNumberOfPieces>10</_011:totalNumberOfPieces>\r\n"
		+ "                  <_011:totalWeight>100.000</_011:totalWeight>\r\n"
		+ "                  <_011:totalDisplayWeight>100.000</_011:totalDisplayWeight>\r\n"
		+ "                  <_011:totalVolume>1.000</_011:totalVolume>\r\n"
		+ "                  <_011:totalVolumeThreeDecimal>1.000</_011:totalVolumeThreeDecimal>\r\n"
		+ "                  <_011:isAWBDataCaptureDone>false</_011:isAWBDataCaptureDone>\r\n"
		+ "                  <_011:lastUpdateUser>SATS</_011:lastUpdateUser>\r\n"
		+ "                  <_011:lastUpdateTime>07-Sep-2021 12:28:57.909</_011:lastUpdateTime>\r\n"
		+ "               </_011:shipmentDetails>\r\n"
		+ "               <_011:bookingCommodityDetails>\r\n"
		+ "                  <_011:serialNumber>8</_011:serialNumber>\r\n"
		+ "                  <_011:commodityCode>GEN</_011:commodityCode>\r\n"
		+ "                  <_011:pieces>10</_011:pieces>\r\n"
		+ "                  <_011:weight>100.000</_011:weight>\r\n"
		+ "                  <_011:displayWeight>100.000</_011:displayWeight>\r\n"
		+ "                  <_011:volume>1.000</_011:volume>\r\n"
		+ "                  <_011:grossVolume>0.200</_011:grossVolume>\r\n"
		+ "                  <_011:displayGrossVolume>0.200</_011:displayGrossVolume>\r\n"
		+ "                  <_011:volumeThreeDecimal>1.000</_011:volumeThreeDecimal>\r\n"
		+ "                  <_011:shipmentDescription>GENERAL CARGO</_011:shipmentDescription>\r\n"
		+ "                  <_011:sccCode>GEN</_011:sccCode>\r\n"
		+ "                  <_011:chargeableWeight>167.000</_011:chargeableWeight>\r\n"
		+ "                  <_011:displayChargableWeight>167.000</_011:displayChargableWeight>\r\n"
		+ "                  <_011:handlingCodes>\r\n"
		+ "                     <_011:handlingCode>\r\n"
		+ "                        <code>GEN</code>\r\n"
		+ "                        <prioritySequence>20</prioritySequence>\r\n"
		+ "                     </_011:handlingCode>\r\n"
		+ "                  </_011:handlingCodes>\r\n"
		+ "                  <_011:ratingDetails>\r\n"
		+ "                     <_011:totalTaxes>0</_011:totalTaxes>\r\n"
		+ "                     <_011:marketRate>100.0000</_011:marketRate>\r\n"
		+ "                     <_011:marketRateInSystemCurrency>100.0000</_011:marketRateInSystemCurrency>\r\n"
		+ "                     <_011:marketCharge>16700.000</_011:marketCharge>\r\n"
		+ "                     <_011:marketChargeInSystemCurrency>16700.000</_011:marketChargeInSystemCurrency>\r\n"
		+ "                  </_011:ratingDetails>\r\n"
		+ "               </_011:bookingCommodityDetails>\r\n"
		+ "               <_011:bookingFlightDetails>\r\n"
		+ "                  <_011:serialNumber>11</_011:serialNumber>\r\n"
		+ "                  <_011:segmentOrigin>SIN</_011:segmentOrigin>\r\n"
		+ "                  <_011:segmentDestination>CDG</_011:segmentDestination>\r\n"
		+ "                  <_011:carrierCode>SQ</_011:carrierCode>\r\n"
		+ "                  <_011:flightNumber>1083</_011:flightNumber>\r\n"
		+ "                  <_011:segmentDepartureDate>08-Sep-2021 06:00:00</_011:segmentDepartureDate>\r\n"
		+ "                  <_011:segmentDepartureDateUTC>07-Sep-2021 22:00:00</_011:segmentDepartureDateUTC>\r\n"
		+ "                  <_011:pieces>0</_011:pieces>\r\n"
		+ "                  <_011:weight>100.000</_011:weight>\r\n"
		+ "                  <_011:displayWeight>100.000</_011:displayWeight>\r\n"
		+ "                  <_011:confirmedWeight>100.000</_011:confirmedWeight>\r\n"
		+ "                  <_011:confirmedVolume>1.000</_011:confirmedVolume>\r\n"
		+ "                  <_011:allotmentId>FS</_011:allotmentId>\r\n"
		+ "                  <_011:aircraftType>320</_011:aircraftType>\r\n"
		+ "                  <_011:flightBookingStatus>C</_011:flightBookingStatus>\r\n"
		+ "                  <_011:routeNumber>1</_011:routeNumber>\r\n"
		+ "                  <_011:flightSegNumber>1</_011:flightSegNumber>\r\n"
		+ "                  <_011:shipmentRank>2</_011:shipmentRank>\r\n"
		+ "                  <_011:flightDate>08-Sep-2021</_011:flightDate>\r\n"
		+ "                  <_011:segmentArrivalDate>08-Sep-2021 14:00:00</_011:segmentArrivalDate>\r\n"
		+ "                  <_011:segmentArrivalDateUTC>07-Sep-2021 12:00:00</_011:segmentArrivalDateUTC>\r\n"
		+ "                  <_011:segmentSerialNumber>1</_011:segmentSerialNumber>\r\n"
		+ "                  <_011:flightCarrierId>1618</_011:flightCarrierId>\r\n"
		+ "                  <_011:flightSequenceNumber>1</_011:flightSequenceNumber>\r\n"
		+ "                  <_011:truckIndicator>N</_011:truckIndicator>\r\n"
		+ "               </_011:bookingFlightDetails>\r\n"
		+ "               <_011:shipmentScreeningInformation/>\r\n"
		+ "               <_011:uniqueReference>\r\n"
		+ "                  <_011:uniqueReferenceTwo>SQSIN2318AUT01A</_011:uniqueReferenceTwo>\r\n"
		+ "               </_011:uniqueReference>\r\n"
		+ "            </_011:bookingDetails>\r\n"
		+ "            <!--Zero or more repetitions:-->\r\n"
		+ "         </_011:requestData>\r\n"
		+ "      </_01:SaveBookingDetailsRequest>\r\n"
		+ "   </soapenv:Body>\r\n"
		+ "</soapenv:Envelope>\r\n"
		+ "";
}
