
package com.ngen.cosys.icms.schema.bookingapi.services.capacitybookingservice._2013._06._04_01;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CapacityBookingService", targetNamespace = "http://www.ibsplc.com/icargo/services/CapacityBookingService/2013/06/04_01", wsdlLocation = "file:/D:/Dump/CR154/BookingAPI_XSD/capacity/booking/standard/CapacityBookingService.wsdl")
public class CapacityBookingService_Service
    extends Service
{

    private final static URL CAPACITYBOOKINGSERVICE_WSDL_LOCATION;
    private final static WebServiceException CAPACITYBOOKINGSERVICE_EXCEPTION;
    private final static QName CAPACITYBOOKINGSERVICE_QNAME = new QName("http://www.ibsplc.com/icargo/services/CapacityBookingService/2013/06/04_01", "CapacityBookingService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/Dump/CR154/BookingAPI_XSD/capacity/booking/standard/CapacityBookingService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CAPACITYBOOKINGSERVICE_WSDL_LOCATION = url;
        CAPACITYBOOKINGSERVICE_EXCEPTION = e;
    }

    public CapacityBookingService_Service() {
        super(__getWsdlLocation(), CAPACITYBOOKINGSERVICE_QNAME);
    }

    public CapacityBookingService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CAPACITYBOOKINGSERVICE_QNAME, features);
    }

    public CapacityBookingService_Service(URL wsdlLocation) {
        super(wsdlLocation, CAPACITYBOOKINGSERVICE_QNAME);
    }

    public CapacityBookingService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CAPACITYBOOKINGSERVICE_QNAME, features);
    }

    public CapacityBookingService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CapacityBookingService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CapacityBookingService
     */
    @WebEndpoint(name = "CapacityBookingServiceHTTP")
    public CapacityBookingService getCapacityBookingServiceHTTP() {
        return super.getPort(new QName("http://www.ibsplc.com/icargo/services/CapacityBookingService/2013/06/04_01", "CapacityBookingServiceHTTP"), CapacityBookingService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CapacityBookingService
     */
    @WebEndpoint(name = "CapacityBookingServiceHTTP")
    public CapacityBookingService getCapacityBookingServiceHTTP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.ibsplc.com/icargo/services/CapacityBookingService/2013/06/04_01", "CapacityBookingServiceHTTP"), CapacityBookingService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CAPACITYBOOKINGSERVICE_EXCEPTION!= null) {
            throw CAPACITYBOOKINGSERVICE_EXCEPTION;
        }
        return CAPACITYBOOKINGSERVICE_WSDL_LOCATION;
    }

}
