
package com.ngen.cosys.icms.schema.bookingapi.services.capacitybookingservice._2013._06._04_01;

import javax.xml.ws.WebFault;
import com.ngen.cosys.icms.schema.bookingapi.framework.services.jaxws.types.common.ServiceFaultDetail;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "ServiceFault", targetNamespace = "http://www.ibsplc.com/icargo/services/CapacityBookingService/2013/06/04_01")
public class ServiceFault
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ServiceFaultDetail faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ServiceFault(String message, ServiceFaultDetail faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public ServiceFault(String message, ServiceFaultDetail faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.ibsplc.icargo.framework.services.jaxws.types.common.ServiceFaultDetail
     */
    public ServiceFaultDetail getFaultInfo() {
        return faultInfo;
    }

}
