insert into CUSTOMER_MASTER ( CUSTOMERCODE ,CUSTOMERSHORTNAME ) values ('DHL','EXP');

INSERT INTO CUSTOMER_TYPES ( CUSTOMER_ID ,CUSTOMERTYPECODE ) VALUES (1,'AGT');

INSERT INTO CUSTOMER_LOCATION ( CUSTOMERLOCATIONID ,CUSTOMERID ,DELIVERYLOCATION ) VALUES (1,1,'BANGALORE');