//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.29 at 04:11:16 PM SGT 
//


package com.ngen.cosys.ulms.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FlightNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="FlightDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ImportExportFlag" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="AssociatedAssociatedPDList" type="{http://www.sats.com.sg/uldAssociationWebservice}ULDDetail"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "flightNumber",
    "flightDate",
    "importExportFlag",
    "associatedAssociatedPDList"
})
@XmlRootElement(name = "FlightULDPDAssociationRequest")
public class FlightULDPDAssociationRequest {

    @XmlElement(name = "FlightNumber", required = true)
    protected String flightNumber;
    @XmlElement(name = "FlightDate", required = true)
    protected String flightDate;
    @XmlElement(name = "ImportExportFlag", required = true)
    protected String importExportFlag;
    @XmlElement(name = "AssociatedAssociatedPDList", required = true)
    protected ULDDetail associatedAssociatedPDList;

    /**
     * Gets the value of the flightNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlightNumber() {
        return flightNumber;
    }

    /**
     * Sets the value of the flightNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlightNumber(String value) {
        this.flightNumber = value;
    }

    /**
     * Gets the value of the flightDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlightDate() {
        return flightDate;
    }

    /**
     * Sets the value of the flightDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlightDate(String value) {
        this.flightDate = value;
    }

    /**
     * Gets the value of the importExportFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportExportFlag() {
        return importExportFlag;
    }

    /**
     * Sets the value of the importExportFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportExportFlag(String value) {
        this.importExportFlag = value;
    }

    /**
     * Gets the value of the associatedAssociatedPDList property.
     * 
     * @return
     *     possible object is
     *     {@link ULDDetail }
     *     
     */
    public ULDDetail getAssociatedAssociatedPDList() {
        return associatedAssociatedPDList;
    }

    /**
     * Sets the value of the associatedAssociatedPDList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ULDDetail }
     *     
     */
    public void setAssociatedAssociatedPDList(ULDDetail value) {
        this.associatedAssociatedPDList = value;
    }

}
