//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.29 at 04:11:16 PM SGT 
//


package com.ngen.cosys.ulms.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for FlightChangeDetail complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="FlightChangeDetail"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="OldFlightNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="OldFLightDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="NewFLightNumber" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="NewFLightDate" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ImportExportFlag" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="STD" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="STA" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ACReg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Bay" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ChangedULDBTList" type="{http://www.sats.com.sg/uldAssociationWebservice}ULDDetail" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "FlightChangeDetail", propOrder = {
    "oldFlightNumber",
    "oldFLightDate",
    "newFLightNumber",
    "newFLightDate",
    "importExportFlag",
    "std",
    "sta",
    "acReg",
    "bay",
    "changedULDBTList"
})
public class FlightChangeDetail {

    @XmlElement(name = "OldFlightNumber", required = true)
    protected String oldFlightNumber;
    @XmlElement(name = "OldFLightDate", required = true)
    protected String oldFLightDate;
    @XmlElement(name = "NewFLightNumber",nillable = true)
    protected String newFLightNumber;
    @XmlElement(name = "NewFLightDate",nillable = true)
    protected String newFLightDate;
    @XmlElement(name = "ImportExportFlag", required = true)
    protected String importExportFlag;
    @XmlElement(name = "STD",nillable = true)
    protected String std;
    @XmlElement(name = "STA",nillable = true)
    protected String sta;
    @XmlElement(name = "ACReg",nillable = true)
    protected String acReg;
    @XmlElement(name = "Bay",nillable = true)
    protected String bay;
    @XmlElement(name = "ChangedULDBTList")
    protected ULDDetail changedULDBTList;

    /**
     * Gets the value of the oldFlightNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOldFlightNumber() {
        return oldFlightNumber;
    }

    /**
     * Sets the value of the oldFlightNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOldFlightNumber(String value) {
        this.oldFlightNumber = value;
    }

    /**
     * Gets the value of the oldFLightDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOldFLightDate() {
        return oldFLightDate;
    }

    /**
     * Sets the value of the oldFLightDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOldFLightDate(String value) {
        this.oldFLightDate = value;
    }

    /**
     * Gets the value of the newFLightNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewFLightNumber() {
        return newFLightNumber;
    }

    /**
     * Sets the value of the newFLightNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewFLightNumber(String value) {
        this.newFLightNumber = value;
    }

    /**
     * Gets the value of the newFLightDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getNewFLightDate() {
        return newFLightDate;
    }

    /**
     * Sets the value of the newFLightDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setNewFLightDate(String value) {
        this.newFLightDate = value;
    }

    /**
     * Gets the value of the importExportFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportExportFlag() {
        return importExportFlag;
    }

    /**
     * Sets the value of the importExportFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportExportFlag(String value) {
        this.importExportFlag = value;
    }

    /**
     * Gets the value of the std property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTD() {
        return std;
    }

    /**
     * Sets the value of the std property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTD(String value) {
        this.std = value;
    }

    /**
     * Gets the value of the sta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTA() {
        return sta;
    }

    /**
     * Sets the value of the sta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTA(String value) {
        this.sta = value;
    }

    /**
     * Gets the value of the acReg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACReg() {
        return acReg;
    }

    /**
     * Sets the value of the acReg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACReg(String value) {
        this.acReg = value;
    }

    /**
     * Gets the value of the bay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBay() {
        return bay;
    }

    /**
     * Sets the value of the bay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBay(String value) {
        this.bay = value;
    }

    /**
     * Gets the value of the changedULDBTList property.
     * 
     * @return
     *     possible object is
     *     {@link ULDDetail }
     *     
     */
    public ULDDetail getChangedULDBTList() {
        return changedULDBTList;
    }

    /**
     * Sets the value of the changedULDBTList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ULDDetail }
     *     
     */
    public void setChangedULDBTList(ULDDetail value) {
        this.changedULDBTList = value;
    }

}
