//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2021.04.29 at 04:11:16 PM SGT 
//


package com.ngen.cosys.ulms.model;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="FlightNumber" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="FlightDate" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ImportExportFlag" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="STD" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="STA" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="ACReg" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="Bay" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/&gt;
 *         &lt;element name="ULDBTList" type="{http://www.sats.com.sg/uldAssociationWebservice}ULDDetail"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "flightNumber",
    "flightDate",
    "importExportFlag",
    "std",
    "sta",
    "acReg",
    "bay",
    "uldbtList"
})
@XmlRootElement(name = "FlightAssignedULDResponse")
public class FlightAssignedULDResponse {

    @XmlElement(name = "FlightNumber", required = true)
    protected String flightNumber;
    @XmlElement(name = "FlightDate", required = true)
    protected String flightDate;
    @XmlElement(name = "ImportExportFlag", required = true)
    protected String importExportFlag;
    @XmlElement(name = "STD", nillable = true)
    protected String std;
    @XmlElement(name = "STA", nillable = true)
    protected String sta;
    @XmlElement(name = "ACReg", nillable = true)
    protected String acReg;
    @XmlElement(name = "Bay", nillable = true)
    protected String bay;
    @XmlElement(name = "ULDBTList", required = true)
    protected ULDDetail uldbtList;

    /**
     * Gets the value of the flightNumber property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlightNumber() {
        return flightNumber;
    }

    /**
     * Sets the value of the flightNumber property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlightNumber(String value) {
        this.flightNumber = value;
    }

    /**
     * Gets the value of the flightDate property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFlightDate() {
        return flightDate;
    }

    /**
     * Sets the value of the flightDate property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFlightDate(String value) {
        this.flightDate = value;
    }

    /**
     * Gets the value of the importExportFlag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportExportFlag() {
        return importExportFlag;
    }

    /**
     * Sets the value of the importExportFlag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportExportFlag(String value) {
        this.importExportFlag = value;
    }

    /**
     * Gets the value of the std property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTD() {
        return std;
    }

    /**
     * Sets the value of the std property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTD(String value) {
        this.std = value;
    }

    /**
     * Gets the value of the sta property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSTA() {
        return sta;
    }

    /**
     * Sets the value of the sta property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSTA(String value) {
        this.sta = value;
    }

    /**
     * Gets the value of the acReg property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getACReg() {
        return acReg;
    }

    /**
     * Sets the value of the acReg property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setACReg(String value) {
        this.acReg = value;
    }

    /**
     * Gets the value of the bay property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBay() {
        return bay;
    }

    /**
     * Sets the value of the bay property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBay(String value) {
        this.bay = value;
    }

    /**
     * Gets the value of the uldbtList property.
     * 
     * @return
     *     possible object is
     *     {@link ULDDetail }
     *     
     */
    public ULDDetail getULDBTList() {
        return uldbtList;
    }

    /**
     * Sets the value of the uldbtList property.
     * 
     * @param value
     *     allowed object is
     *     {@link ULDDetail }
     *     
     */
    public void setULDBTList(ULDDetail value) {
        this.uldbtList = value;
    }

}
